const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const fs = require('node:fs'); const path = require('node:path'); const crypto = require('node:crypto');
const ROOT = path.resolve(__dirname, '..');
const PROJECT = __dirname;
const OUT = path.join(PROJECT, 'outputs', 'ralskies-content-engine');
const STATE = path.join(OUT, 'phase2_upload_state.json');
const INSPECT = path.join(OUT, 'Ralskies_Upload_Tracker.xlsx.inspect.ndjson');
const SETTINGS = path.join(OUT, 'desktop_settings.json');
const BATCH_TRANSACTION = path.join(OUT, 'bulk_preparation_transaction.json');
const TRACKER = path.join(OUT, 'Ralskies_Upload_Tracker.xlsx');
function walk(dir){let out=[]; for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name); if(e.isDirectory()&&e.name!=='node_modules'&&!f.includes(`${path.sep}.git${path.sep}`))out.push(...walk(f)); else if(e.isFile()&&e.name.toLowerCase().endsWith('.mp4'))out.push(f)} return out}
function digest(file){return new Promise((ok,no)=>{const h=crypto.createHash('sha256');fs.createReadStream(file).on('error',no).on('data',x=>h.update(x)).on('end',()=>ok(h.digest('hex')))})}
function dashboard(){if(!fs.existsSync(INSPECT))return {}; const lines=fs.readFileSync(INSPECT,'utf8').split(/\\r?\\n/).filter(Boolean); const t=lines.map(x=>JSON.parse(x)).find(x=>x.kind==='table'&&x.sheet==='Dashboard'); const r={}; for(const row of t?.values||[])if(row?.[0])r[String(row[0])]=row[1]; return r}
async function inventory(){const files=await Promise.all(walk(ROOT).map(async file=>({file:path.relative(ROOT,file),name:path.basename(file),hash:await digest(file),size:fs.statSync(file).size,status:'REVIEW'}))); const state=fs.existsSync(STATE)?JSON.parse(fs.readFileSync(STATE,'utf8')):{}; return {files,dashboard:dashboard(),state,scannedAt:new Date().toISOString()}}
ipcMain.handle('engine:inventory',inventory);
ipcMain.handle('engine:calendar',()=>{const file=path.join(OUT,'prepared_queue.json'); return fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):[]});
ipcMain.handle('engine:batches',async()=>{if(!fs.existsSync(BATCH_TRANSACTION))return null; const data=JSON.parse(fs.readFileSync(BATCH_TRANSACTION,'utf8')); try { const {readTracker}=await import('./core/tracker-service.mjs'); const {reconcileBatchState}=await import('./core/staging-service.mjs'); const rows=await readTracker(TRACKER); data.batches=(data.batches||[]).map(batch=>({...batch,reconciled:reconcileBatchState(batch,rows)})); } catch (error) { data.reconciliationError=error.message; } return data});
ipcMain.handle('engine:preview-batch',async(_e,batchId='BULK_01')=>{const {previewBatch}=await import('./core/staging-service.mjs'); return previewBatch({transactionPath:BATCH_TRANSACTION,trackerPath:TRACKER,batchId})});
ipcMain.handle('engine:discover-private',async(_e,batchId='BULK_02')=>{const {discoverPrivateBatch}=await import('./core/youtube-service.mjs'); return discoverPrivateBatch({batchId})});
ipcMain.handle('engine:confirm-matches',async(_e,payload)=>{const {confirmMatches}=await import('./core/match-confirmation.mjs'); return confirmMatches({discovery:payload.discovery,trackerPath:TRACKER,batchId:payload.batchId||'BULK_02'})});
ipcMain.handle('engine:verify-confirmed',async(_e,batchId='BULK_02')=>{const {verifyConfirmedBatch}=await import('./core/youtube-service.mjs'); return verifyConfirmedBatch({batchId})});
ipcMain.handle('engine:preview-metadata',async(_e,batchId='BULK_02')=>{const {previewMetadataSchedule}=await import('./core/youtube-service.mjs'); return previewMetadataSchedule({batchId})});
ipcMain.handle('engine:reconcile-readonly',async(_e,p)=>{try{const {reconcileReadOnly}=await import('./core/recovery-service.mjs');const result=await reconcileReadOnly({journalRow:p.journalRow,readRemote:async()=>p.mockRemote});return {ok:true,status:result.state==='REMOTE_STATE_VERIFIED'?'VERIFIED':'RECONCILIATION_REQUIRED',executionId:p.executionId||null,shortId:p.shortId||null,youtubeId:p.journalRow?.youtube_video_id||null,firstReadPassed:Boolean(result.first?.pass),secondReadPassed:Boolean(result.second?.pass),fields:[...(result.first?.mismatches||[]),...(result.second?.mismatches||[])].map(x=>({field:String(x.field),expected:x.expected??null,actual:x.actual??null,match:false}))};}catch(error){return {ok:false,code:'RECONCILIATION_FAILED',message:String(error.message||error)}}});
ipcMain.handle('engine:recovery-journals',()=>{if(!fs.existsSync(OUT))return [];return fs.readdirSync(OUT).filter(f=>f.toLowerCase().includes('journal')||f.includes('execution')).map(f=>{try{return JSON.parse(fs.readFileSync(path.join(OUT,f),'utf8'))}catch{return null}}).filter(Boolean).flatMap(j=>(j.rows||[]).filter(r=>['APPLIED','APPLIED_UNVERIFIED','VERIFYING','VERIFIED_PENDING_TRACKER','RECONCILIATION_REQUIRED'].includes(String(r.state||'').toUpperCase())).map(r=>({...r,state:String(r.state||'').toUpperCase(),execution_id:j.execution_id,batch_id:j.batch_id,short_id:r.short_id||r.shortId||'',youtube_video_id:r.youtube_video_id||r.youtubeVideoId||''})));});
ipcMain.handle('engine:finalize-recovery',async(_e,p)=>{if(!p?.reconciliation||p.reconciliation.status!=='VERIFIED'||p.reconciliation.firstReadPassed!==true||p.reconciliation.secondReadPassed!==true)return {ok:false,code:'RECONCILIATION_NOT_VERIFIED',message:'Finalize Tracker requires two successful read-only verifications.'};try{const {finalizeTracker}=await import('./core/recovery-service.mjs');const result=await finalizeTracker({trackerPath:TRACKER,shortId:p.shortId,reason:p.reason||'INTERRUPTED_AFTER_REMOTE_WRITE'});return {ok:true,status:'COMPLETE',executionId:p.executionId||null,shortId:p.shortId,trackerUpdated:true,journalState:'COMPLETE',reconciliationReason:p.reason||'INTERRUPTED_AFTER_REMOTE_WRITE',backup:result.backup};}catch(error){return {ok:false,code:'TRACKER_FINALIZATION_FAILED',message:String(error.message||error)}}});
ipcMain.handle('engine:production-review',async(_e,batchId='BULK_02')=>{const {readTracker}=await import('./core/tracker-service.mjs');const {buildProductionReview}=await import('./core/production-review.mjs');const rows=await readTracker(TRACKER);let recovery=[];if(fs.existsSync(OUT)){for(const f of fs.readdirSync(OUT)){if(!(f.toLowerCase().includes('journal')||f.includes('execution')))continue;try{const j=JSON.parse(fs.readFileSync(path.join(OUT,f),'utf8'));recovery.push(...(j.rows||[]))}catch{}}}const model=buildProductionReview({batchId,rows,recoveryRows:recovery});const plan=model.plan;return {...model,plan:{executionId:plan.executionId,batchId:plan.batchId,mode:plan.mode,approvedRowIds:[...plan.approvedRowIds],youtubeIds:[...plan.youtubeIds],operationCount:plan.operationCount,createdAt:plan.createdAt}}});
ipcMain.handle('engine:apply-production',async(_e,p)=>{if(p?.executeReal===true)return {ok:false,code:'REAL_PRODUCTION_EXECUTION_DISABLED'};const {executeProductionRequest}=await import('./core/production-entry.mjs');return executeProductionRequest({...p,rows:[],write:async()=>{},read:async()=>{},trackerUpdate:async()=>{}})});
ipcMain.handle('engine:apply-metadata',async(_e,p)=>{if(!p?.executionPlan)throw Error('NO_EXECUTION_PLAN');if(p.dryRun!==true)throw Error('PRODUCTION_APPLY_REQUIRES_EXPLICIT_APPROVAL');const {runPlannedExecution}=await import('./core/production-runner.mjs');const {readTracker}=await import('./core/tracker-service.mjs');return runPlannedExecution({executionPlan:p.executionPlan,rows:await readTracker(TRACKER),mode:'DRY_RUN',read:async()=>{}})});
ipcMain.handle('engine:title-recommend',async(_e,shortId)=>{const {readTracker}=await import('./core/tracker-service.mjs');const {recommendTitle}=await import('./core/title-intelligence.mjs');const row=(await readTracker(TRACKER)).find(r=>String(r.short_id)===String(shortId));if(!row)throw Error('Short not found');return recommendTitle(row)});
ipcMain.handle('engine:title-audit',async()=>{const {readTracker}=await import('./core/tracker-service.mjs');const {auditTitle}=await import('./core/title-intelligence.mjs');return (await readTracker(TRACKER)).map(auditTitle).filter(x=>x.audit==='TITLE_REVIEW_RECOMMENDED')});
ipcMain.handle('engine:title-review-queue',async()=>{const {readTracker}=await import('./core/tracker-service.mjs');const {auditTitle,recommendTitle}=await import('./core/title-intelligence.mjs');const {HUMAN_EDIT_CANDIDATES}=await import('./core/recommendation-variety.mjs');const rows=(await readTracker(TRACKER)).map(auditTitle).filter(x=>x.health!=='TITLE_HEALTHY'&&x.title_review_status!=='TITLE_KEEP_CURRENT').sort((a,b)=>String(a.priority).localeCompare(String(b.priority))||String(a.health).localeCompare(String(b.health)));return Promise.all(rows.map(async row=>({...row,recommendations:(await recommendTitle(row)).recommendations.concat(HUMAN_EDIT_CANDIDATES[row.short_id]?[{title:HUMAN_EDIT_CANDIDATES[row.short_id],family:'HUMAN_EDIT',score:null,warnings:[],supporting_examples:[]}]:[])})));});
ipcMain.handle('engine:approve-title',async(_e,p)=>{const {approveTitle}=await import('./core/title-approval.mjs');return approveTitle({shortId:p.shortId,title:p.title,family:p.family,source:p.source,trackerPath:TRACKER})});
ipcMain.handle('engine:keep-title',async(_e,shortId)=>{const {keepCurrentTitle}=await import('./core/title-approval.mjs');return keepCurrentTitle({shortId,trackerPath:TRACKER})});
ipcMain.handle('engine:settings',()=>fs.existsSync(SETTINGS)?JSON.parse(fs.readFileSync(SETTINGS,'utf8')):{timezone:'Asia/Manila',slots:['17:30','22:30'],optionalSlot:'01:30',protectedWindow:'20:00–21:00',shortsPerDay:2,dryRun:true});
ipcMain.handle('engine:save-settings',(_e,settings)=>{fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(SETTINGS,JSON.stringify(settings,null,2));return settings});
ipcMain.handle('engine:choose-folder',()=>dialog.showOpenDialogSync({properties:['openDirectory']})?.[0]||null);
ipcMain.handle('engine:dry-run',(_e,action)=>({action,dryRun:true,message:'No files, tracker rows, or YouTube resources were modified.'}));
function createWindow(){const win=new BrowserWindow({width:1440,height:930,minWidth:1100,minHeight:700,backgroundColor:'#0b1020',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'renderer','index.html'))}
app.whenReady().then(()=>{createWindow();app.on('activate',()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})}); app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});







