#!/usr/bin/env node
// Deterministic local pipeline. No LLM or Studio automation is used.
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
// The project lives in desktop/; finished Shorts remain in the sibling folders at the workspace root.
const ROOT=path.resolve(import.meta.dirname,'..'), PROJECT=import.meta.dirname, OUT=path.join(PROJECT,'outputs','ralskies-content-engine');
const cfg={tracker:process.env.RALSKIES_TRACKER||path.join(OUT,'Ralskies_Upload_Tracker.csv'), state:path.join(OUT,'cli_state.json'), exceptions:path.join(OUT,'exceptions.json'), slots:['17:30','22:30'], optional:'01:30', tz:'Asia/Manila'};
const arg=process.argv.slice(2), cmd=arg[0]||'help', dry=arg.includes('--dry-run');
function csv(s){let lines=s.split(/\r?\n/).filter(Boolean); if(!lines.length)return[]; let h=lines.shift().split(',').map(x=>x.trim()); return lines.map(l=>{let v=l.split(','); return Object.fromEntries(h.map((k,i)=>[k,(v[i]||'').trim()]));});}
function readRows(){if(!fs.existsSync(cfg.tracker)) throw new Error(`Tracker CSV not found: ${cfg.tracker}. Export Ralskies_Upload_Tracker.xlsx to CSV or set RALSKIES_TRACKER.`); return csv(fs.readFileSync(cfg.tracker,'utf8'));}
function hash(f){return new Promise((res,rej)=>{let h=crypto.createHash('sha256'); fs.createReadStream(f).on('error',rej).on('data',d=>h.update(d)).on('end',()=>res(h.digest('hex')));});}
async function scan(){let rows=readRows(), files=fs.readdirSync(ROOT,{recursive:true}).filter(f=>f.toLowerCase().endsWith('.mp4')); let seen=new Map(), exceptions=[]; for(const rel of files){let p=path.join(ROOT,rel), sha=await hash(p); if(seen.has(sha)||rows.some(r=>r.sha256?.toLowerCase()===sha&&['SCHEDULED','PUBLISHED','DUPLICATE'].includes((r.status||'').toUpperCase()))) exceptions.push({type:'DUPLICATE',path:p,sha256:sha}); else seen.set(sha,p);} fs.mkdirSync(OUT,{recursive:true}); fs.writeFileSync(cfg.exceptions,JSON.stringify(exceptions,null,2)); console.log(`${files.length} MP4 files scanned; ${exceptions.length} exceptions. ${cfg.exceptions}`);}
function nextSlots(start){let d=new Date(start); let out=[]; for(let i=0;i<365;i++){let day=new Date(d); day.setDate(d.getDate()+Math.floor(i/2)); let slot=cfg.slots[i%2]; out.push(`${day.toISOString().slice(0,10)}T${slot}:00+08:00`);} return out;}
function prepare(){let rows=readRows().filter(r=>['APPROVED','UPLOAD_READY','ANALYZED'].includes((r.status||'').toUpperCase())&&!['DUPLICATE','FAILED'].includes((r.status||'').toUpperCase())); let slots=nextSlots(new Date()); let n=0; for(const r of rows){if(!r.scheduled_time) r.scheduled_time=slots[n++]; r.status='UPLOAD_READY';} if(dry){console.log(JSON.stringify(rows.slice(0,20),null,2)); console.log(`DRY RUN: ${rows.length} eligible rows; no files or tracker modified.`); return;} fs.writeFileSync(path.join(OUT,'prepared_queue.json'),JSON.stringify(rows,null,2)); console.log(`Prepared ${rows.length} rows. Queue: ${path.join(OUT,'prepared_queue.json')}`);}
function help(){console.log('ralskies scan | prepare [--dry-run] | upload | verify | report | dry-run');}
try{if(cmd==='scan') await scan(); else if(cmd==='prepare'||cmd==='dry-run') prepare(); else if(['upload','verify','report'].includes(cmd)) console.log(`${cmd}: integration hook ready; requires OAuth/API module and approved queue.`); else help();}catch(e){console.error('ERROR:',e.message); process.exitCode=1;}
