import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import initSqlJs from 'sql.js';

const require=createRequire(import.meta.url);
const DB_NAME='creative-memory.sqlite';
const PROMPT_VERSION='ralskies_metadata_v4_rag';
const locks=new Map();
let sqlPromise;
const clean=value=>String(value??'').trim();
const norm=value=>clean(value).normalize('NFKC').toLowerCase();
const json=value=>JSON.stringify(value??null);
const parse=value=>{try{return JSON.parse(value||'null')}catch{return null}};
const hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');

async function sql(){if(!sqlPromise)sqlPromise=initSqlJs({locateFile:file=>require.resolve('sql.js/dist/'+file)});return sqlPromise;}
function migrate(db){
 db.run('PRAGMA foreign_keys=ON');
 db.run(`CREATE TABLE IF NOT EXISTS creative_title_memory (
 memory_id TEXT PRIMARY KEY,generation_id TEXT NOT NULL,candidate_index INTEGER NOT NULL,
 created_at TEXT NOT NULL,updated_at TEXT NOT NULL,asset_hash TEXT,batch_id TEXT,short_id TEXT,
 song TEXT,source TEXT,original_artist TEXT,niche TEXT,content_type TEXT,angle_family TEXT,
 generated_title TEXT,approved_title TEXT,generated_description TEXT,approved_description TEXT,
 generated_hashtags TEXT,approved_hashtags TEXT,selected_candidate_index INTEGER,
 decision TEXT NOT NULL DEFAULT 'PENDING',edited_by_user INTEGER NOT NULL DEFAULT 0,
 approved_by_user INTEGER NOT NULL DEFAULT 0,rejected INTEGER NOT NULL DEFAULT 0,rejection_reason TEXT,
 active_for_rag INTEGER NOT NULL DEFAULT 0,published INTEGER NOT NULL DEFAULT 0,published_at TEXT,
 youtube_video_id TEXT,model_name TEXT,prompt_version TEXT,title_opening TEXT,sentence_shape TEXT,
 UNIQUE(generation_id,candidate_index))`);
 db.run(`CREATE TABLE IF NOT EXISTS creative_memory_events (
 event_id TEXT PRIMARY KEY,memory_id TEXT NOT NULL,event_at TEXT NOT NULL,event_type TEXT NOT NULL,
 payload_json TEXT NOT NULL,FOREIGN KEY(memory_id) REFERENCES creative_title_memory(memory_id))`);
 db.run('CREATE TABLE IF NOT EXISTS creative_memory_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL)');
 db.run("INSERT OR REPLACE INTO creative_memory_meta(key,value) VALUES ('schema_version','1')");
 db.run('CREATE INDEX IF NOT EXISTS creative_memory_context_idx ON creative_title_memory(song,source,niche,content_type)');
 db.run('CREATE INDEX IF NOT EXISTS creative_memory_rag_idx ON creative_title_memory(active_for_rag,decision,updated_at)');
}
async function openDb(outputDir){const SQL=await sql(),file=path.join(outputDir,DB_NAME);let bytes;try{bytes=await fs.readFile(file)}catch(error){if(error.code!=='ENOENT')throw error;}const db=new SQL.Database(bytes?new Uint8Array(bytes):undefined);migrate(db);return {db,file};}
async function saveDb(db,file){const bytes=db.export(),temporary=file+'.'+crypto.randomUUID()+'.tmp';await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(temporary,Buffer.from(bytes));await fs.rename(temporary,file);}
async function withDb(outputDir,action,{write=false}={}){const previous=locks.get(outputDir)||Promise.resolve();let release;const current=new Promise(resolve=>{release=resolve});locks.set(outputDir,current);await previous;let opened;try{opened=await openDb(outputDir);const result=await action(opened.db);if(write)await saveDb(opened.db,opened.file);return result}finally{opened?.db.close();release();if(locks.get(outputDir)===current)locks.delete(outputDir);}}
function all(db,sqlText,params=[]){const statement=db.prepare(sqlText);try{statement.bind(params);const result=[];while(statement.step())result.push(statement.getAsObject());return result}finally{statement.free()}}
function one(db,sqlText,params=[]){return all(db,sqlText,params)[0]||null}
function run(db,sqlText,params=[]){const statement=db.prepare(sqlText);try{statement.run(params)}finally{statement.free()}}
function titleOpening(title){return norm(title).replace(/#[\p{L}\p{N}_]+/gu,'').split(/[^\p{L}\p{N}]+/u).filter(Boolean).slice(0,3).join(' ')}
function sentenceShape(text){const value=clean(text);return (value.includes('?')?'QUESTION':value.includes('!')?'EXCLAIM':'STATEMENT')+'_'+(value===value.toLowerCase()?'LOWER':'MIXED')}
function contextOf(suggestion){const c=suggestion.context||{};return {song:clean(c.song),source:clean(c.source),artist:clean(c.artist),niche:clean(c.niche),contentType:clean(c.content_type||c.contentType)}}
function event(db,memoryId,type,payload){run(db,'INSERT INTO creative_memory_events(event_id,memory_id,event_at,event_type,payload_json) VALUES (?,?,?,?,?)',[crypto.randomUUID(),memoryId,new Date().toISOString(),type,json(payload)])}

export async function recordGeneration(outputDir,suggestion){return withDb(outputDir,async db=>{const c=contextOf(suggestion),now=new Date().toISOString();db.run('BEGIN');try{for(let index=0;index<suggestion.candidates.length;index++){const candidate=suggestion.candidates[index],memoryId=hash(suggestion.id+':'+index);if(one(db,'SELECT memory_id FROM creative_title_memory WHERE memory_id=?',[memoryId]))continue;run(db,`INSERT INTO creative_title_memory (memory_id,generation_id,candidate_index,created_at,updated_at,asset_hash,batch_id,short_id,song,source,original_artist,niche,content_type,angle_family,generated_title,generated_description,generated_hashtags,decision,active_for_rag,model_name,prompt_version,title_opening,sentence_shape) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[memoryId,suggestion.id,index,now,now,suggestion.hash,suggestion.batchId,suggestion.shortId,c.song,c.source,c.artist,c.niche,suggestion.contentType||c.contentType,candidate.angle_family||'',candidate.title,candidate.description,json(candidate.tags),'PENDING',0,suggestion.model,PROMPT_VERSION,titleOpening(candidate.title),sentenceShape(candidate.description)]);event(db,memoryId,'GENERATED',{candidateIndex:index});}db.run('COMMIT');return {generationId:suggestion.id,stored:suggestion.candidates.length};}catch(error){db.run('ROLLBACK');throw error}},{write:true})}
export async function recordApproval(outputDir,{suggestion,candidateIndex,approvedTitle,approvedDescription,approvedHashtags,reason='USER_APPROVED'}){return withDb(outputDir,async db=>{const memoryId=hash(suggestion.id+':'+candidateIndex),row=one(db,'SELECT * FROM creative_title_memory WHERE memory_id=?',[memoryId]);if(!row)throw Error('CREATIVE_MEMORY_GENERATION_NOT_FOUND');const title=clean(approvedTitle||row.generated_title),description=clean(approvedDescription||row.generated_description),hashtags=Array.isArray(approvedHashtags)?approvedHashtags:parse(approvedHashtags)||parse(row.generated_hashtags)||[],edited=title!==clean(row.generated_title)||description!==clean(row.generated_description)||json(hashtags)!==json(parse(row.generated_hashtags)||[]);db.run('BEGIN');try{run(db,'UPDATE creative_title_memory SET selected_candidate_index=? WHERE generation_id=?',[candidateIndex,suggestion.id]);run(db,'UPDATE creative_title_memory SET updated_at=?,approved_title=?,approved_description=?,approved_hashtags=?,selected_candidate_index=?,decision=?,edited_by_user=?,approved_by_user=1,rejected=0,active_for_rag=1 WHERE memory_id=?',[new Date().toISOString(),title,description,json(hashtags),candidateIndex,'APPROVED',edited?1:0,memoryId]);event(db,memoryId,'APPROVED',{reason,edited,selectedCandidateIndex:candidateIndex});db.run('COMMIT');return {memoryId,edited}}catch(error){db.run('ROLLBACK');throw error}},{write:true})}
export async function recordRejection(outputDir,{generationId,candidateIndex=0,reason=''}){return withDb(outputDir,async db=>{const memoryId=hash(generationId+':'+candidateIndex);if(!one(db,'SELECT memory_id FROM creative_title_memory WHERE memory_id=?',[memoryId]))throw Error('CREATIVE_MEMORY_GENERATION_NOT_FOUND');run(db,'UPDATE creative_title_memory SET updated_at=?,decision=?,rejected=1,rejection_reason=?,active_for_rag=0 WHERE memory_id=?',[new Date().toISOString(),'REJECTED',clean(reason),memoryId]);event(db,memoryId,'REJECTED',{reason:clean(reason)});return {memoryId,rejected:true}},{write:true})}
function scoreRow(row,q,now){const same=(a,b)=>norm(a)&&norm(a)===norm(b),days=Math.max(0,(now-Date.parse(row.updated_at||row.created_at))/86400000);let score=0;if(same(row.song,q.song))score+=100;if(same(row.source,q.source))score+=60;if(same(row.original_artist,q.artist))score+=45;if(same(row.niche,q.niche))score+=30;if(same(row.content_type,q.contentType))score+=20;if(row.edited_by_user)score+=45;if(row.approved_by_user)score+=20;if(row.published)score+=5;score+=Math.max(0,10-Math.min(Math.floor(days),10));return score}
function diverse(rows,limit=8){const selected=[],families=new Set(),sources=new Set(),openings=new Set(),shapes=new Set();for(const row of rows.sort((a,b)=>b.score-a.score||String(a.memory_id).localeCompare(String(b.memory_id)))){const fresh=!families.has(row.angle_family)||!sources.has(row.source)||!openings.has(row.title_opening)||!shapes.has(row.sentence_shape);if(fresh||selected.length<2){selected.push(row);families.add(row.angle_family);sources.add(row.source);openings.add(row.title_opening);shapes.add(row.sentence_shape)}if(selected.length>=limit)break}return selected}
export async function retrieveCreativeMemory(outputDir,query={}){const result=await withDb(outputDir,async db=>{const now=Date.now(),q={song:clean(query.song),source:clean(query.source),artist:clean(query.artist||query.originalArtist),niche:clean(query.niche),contentType:clean(query.contentType||query.content_type)},approved=all(db,"SELECT * FROM creative_title_memory WHERE active_for_rag=1 AND decision='APPROVED' AND approved_title<>''"),scored=approved.map(row=>({...row,score:scoreRow(row,q,now)})).filter(row=>row.score>0),positive=diverse(scored.sort((a,b)=>b.score-a.score||String(a.memory_id).localeCompare(String(b.memory_id))).slice(0,20),Number(query.positiveLimit)||8).map(row=>({title:row.approved_title,description:row.approved_description,hashtags:parse(row.approved_hashtags)||[],angle_family:row.angle_family,song:row.song,source:row.source,niche:row.niche,edited_by_user:Boolean(row.edited_by_user),score:row.score})),recent=all(db,"SELECT approved_title,angle_family,song,source,niche,updated_at FROM creative_title_memory WHERE active_for_rag=1 AND decision='APPROVED' AND approved_title<>'' ORDER BY updated_at DESC LIMIT 40").filter((row,index,array)=>index===array.findIndex(item=>norm(item.approved_title)===norm(row.approved_title))).slice(0,Number(query.recentLimit)||20).map(row=>({title:row.approved_title,angle_family:row.angle_family,song:row.song,source:row.source,niche:row.niche})),rejected=all(db,"SELECT generated_title,generated_description,rejection_reason,angle_family,song,source,niche,updated_at FROM creative_title_memory WHERE rejected=1 AND decision='REJECTED' ORDER BY updated_at DESC LIMIT 20").map(row=>({...row,score:scoreRow(row,q,now)})).filter(row=>row.score>0).sort((a,b)=>b.score-a.score).slice(0,Number(query.negativeLimit)||2).map(row=>({title:row.generated_title,description:row.generated_description,reason:row.rejection_reason,angle_family:row.angle_family,song:row.song,source:row.source,niche:row.niche}));return {positive_examples:positive,recent_titles:recent,negative_examples:rejected,retrieval_summary:{positive_count:positive.length,manual_edit_count:positive.filter(row=>row.edited_by_user).length,same_source_count:positive.filter(row=>norm(row.source)===norm(q.source)&&norm(q.source)).length,recent_title_count:recent.length,negative_count:rejected.length}}});await fs.mkdir(outputDir,{recursive:true});await fs.appendFile(path.join(outputDir,'creative-memory.log.jsonl'),JSON.stringify({at:new Date().toISOString(),...result.retrieval_summary})+'\n');return result}
export async function memoryStats(outputDir){return withDb(outputDir,async db=>({total:Number(one(db,'SELECT COUNT(*) AS count FROM creative_title_memory').count||0),approved:Number(one(db,"SELECT COUNT(*) AS count FROM creative_title_memory WHERE decision='APPROVED'").count||0),edited:Number(one(db,'SELECT COUNT(*) AS count FROM creative_title_memory WHERE edited_by_user=1').count||0),rejected:Number(one(db,'SELECT COUNT(*) AS count FROM creative_title_memory WHERE rejected=1').count||0),active:Number(one(db,'SELECT COUNT(*) AS count FROM creative_title_memory WHERE active_for_rag=1').count||0),recent:all(db,'SELECT memory_id,created_at,updated_at,song,source,niche,angle_family,generated_title,approved_title,rejection_reason,active_for_rag,decision FROM creative_title_memory ORDER BY updated_at DESC LIMIT 50')}),{write:false})}
export async function listMemory(outputDir,filter='ALL'){const where=filter==='APPROVED'?"WHERE decision='APPROVED'":filter==='EDITED'?'WHERE edited_by_user=1':filter==='REJECTED'?"WHERE rejected=1":'';return withDb(outputDir,async db=>all(db,`SELECT memory_id,created_at,updated_at,song,source,niche,angle_family,generated_title,approved_title,rejection_reason,active_for_rag,decision FROM creative_title_memory ${where} ORDER BY updated_at DESC LIMIT 200`),{write:false})}
export async function setMemoryActive(outputDir,memoryId,active){return withDb(outputDir,async db=>{const row=one(db,'SELECT memory_id FROM creative_title_memory WHERE memory_id=?',[memoryId]);if(!row)throw Error('CREATIVE_MEMORY_NOT_FOUND');run(db,'UPDATE creative_title_memory SET active_for_rag=?,updated_at=? WHERE memory_id=?',[active?1:0,new Date().toISOString(),memoryId]);event(db,memoryId,active?'ENABLED':'DISABLED',{});return {memoryId,active_for_rag:Boolean(active)}},{write:true})}
export const creativeMemoryDbPath=outputDir=>path.join(outputDir,DB_NAME);
export const creativeMemoryPromptVersion=()=>PROMPT_VERSION;