import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { trackerRepository } from './draft-intake.mjs';
import { readTracker, openTracker } from './tracker-service.mjs';
const source=path.resolve('outputs/ralskies-content-engine/Ralskies_Upload_Tracker.xlsx');
const available=await fs.access(source).then(()=>true,()=>false);
test('tracker adapter appends and reads back a new draft without changing old row values or production workbook',{skip:!available},async()=>{
  const digest=async file=>crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex');
  const beforeHash=await digest(source),root=await fs.mkdtemp(path.join(os.tmpdir(),'draft-tracker-')),copy=path.join(root,'tracker.xlsx');
  await fs.copyFile(source,copy);
  const before=await readTracker(copy),repo=await trackerRepository(copy);
  const row={short_id:'TEST-NEW-DRAFT',file_hash:crypto.createHash('sha256').update(crypto.randomUUID()).digest('hex').toUpperCase(),file_name:'New cover.mp4',file_path:'C:/TEST/Drafts/New cover.mp4',original_filename:'New cover.mp4',original_path:'C:/TEST/Drafts/New cover.mp4',current_filename:'test-hash.mp4',current_path:'C:/TEST/Hashed/test-hash.mp4',batch_id:'INTAKE-TEST',status:'AWAITING_METADATA',metadata_state:'AWAITING_METADATA',intake_at:'2026-09-13T00:00:00Z',public_title:'',description:'',youtube_tags:'',category:'',timezone:'Asia/Manila',schedule_eligible:'YES'};
  await repo.commit({additions:[row]});
  await repo.commit({updates:[{short_id:row.short_id,public_title:'New title',scheduled_date:'2027-09-14',scheduled_time:'17:30'}]});
  const after=await readTracker(copy);
  assert.equal(after.length,before.length+1);
  for(let i=0;i<before.length;i++)for(const key of Object.keys(before[i]))assert.deepEqual(after[i][key],before[i][key],'Existing cell changed: '+before[i].short_id+'/'+key);
  assert.equal(after.at(-1).short_id,row.short_id);assert.equal(after.at(-1).public_title,'New title');
  assert.equal(await digest(source),beforeHash);
  const tracker=await openTracker(copy);
  tracker.workbook.recalculate();
  const preview=await tracker.workbook.render({sheetName:'Queue',range:'A'+(after.length-1)+':C'+(after.length+1),scale:1,format:'png'});
  const qa=path.resolve('outputs/draft-pipeline-qa');await fs.mkdir(qa,{recursive:true});await fs.writeFile(path.join(qa,'tracker-after.png'),new Uint8Array(await preview.arrayBuffer()));
  console.log(JSON.stringify({oldRowsPreserved:before.length,newRows:1,productionTrackerUnchanged:true,trackerCopy:copy}));
});
