import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {registerDraftDesktop} from './draft-desktop.mjs';
import {readTracker} from './tracker-service.mjs';
import {writeJson,readJson} from './pipeline-store.mjs';
const source=path.resolve('outputs/ralskies-content-engine/Ralskies_Upload_Tracker.xlsx');
const available=await fs.access(source).then(()=>true,()=>false);
test('desktop watcher, metadata form, stale reservation guard, calendar and stop control work through IPC on a disposable tracker',{skip:!available},async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'draft-desktop-')),outputDir=path.join(root,'output'),draftFolder=path.join(root,'drafts'),trackerPath=path.join(root,'tracker.xlsx');
  await fs.mkdir(outputDir);await fs.mkdir(draftFolder);await fs.copyFile(source,trackerPath);
  const digest=async file=>crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex'),sourceHash=await digest(source);
  const originalRows=await readTracker(trackerPath),handlers=new Map(),notifications=[];let poll,productionBusy=false;
  const service=registerDraftDesktop({ipcMain:{handle:(name,fn)=>handlers.set(name,fn)},outputDir,trackerPath,syncCalendar:()=>readJson(path.join(outputDir,'youtube-calendar.json'),{}),isProductionBusy:()=>productionBusy,onScan:result=>notifications.push(result),startTimer:fn=>{poll=fn;return {};},stopTimer:()=>{}});
  t.after(()=>service.stop());
  const call=(name,p)=>handlers.get('engine:'+name)(null,p);
  await call('draft-configure',{draftFolder,enabled:true});
  const video=path.join(draftFolder,'Latest cover.mp4');await fs.writeFile(video,'isolated test media');const old=new Date(Date.now()-60000);await fs.utimes(video,old,old);
  productionBusy=true;await poll();await fs.access(video);productionBusy=false;
  await poll();assert.equal(notifications.length,1);assert.equal(notifications[0].added,1);await fs.access(video);
  let status=await call('draft-status');const row=status.rows.find(item=>item.original_path===video);assert.equal(row.status,'AWAITING_METADATA');assert.equal(status.settings.hashedFolder,path.join(draftFolder,'hashed'));assert.equal(row.current_path,path.join(draftFolder,'hashed',row.file_hash+'.mp4'));
  await call('draft-metadata',{shortId:row.short_id,metadata:{source_song:'Latest cover',content_type:'ORIGINAL'}});
  const input={batchId:row.batch_id,startDate:'2027-09-13',slots:['17:30'],cadence:'four-per-week'};
  const preview=await call('draft-reserve-preview',input);
  const snapshot={syncedAt:'2027-09-01T00:00:00Z',videos:[{id:'manual',snippet:{title:'Manual'},status:{privacyStatus:'private',publishAt:'2027-09-13T09:30:00Z'}}]};
  await writeJson(path.join(outputDir,'youtube-calendar.json'),snapshot);
  await assert.rejects(call('draft-reserve',{plan:preview}),/STALE/);
  const fresh=await call('draft-reserve-preview',input);assert.equal(fresh.updates[0].scheduled_date,'2027-09-15');
  await call('draft-reserve',{plan:fresh});
  await call('draft-metadata',{shortId:row.short_id,metadata:{public_title:'Latest cover',description:'A new cover performance',youtube_tags:'cover,music',category:'Music'}});
  const calendar=await call('calendar');assert.ok(calendar.events.some(event=>event.shortId===row.short_id&&event.pht==='2027-09-15 17:30'&&event.state==='RESERVED'));
  status=await call('draft-status');assert.equal(status.rows.find(item=>item.short_id===row.short_id).status,'BATCH_READY');
  const disappeared=path.join(root,'drafts-disconnected');await fs.rename(draftFolder,disappeared);
  await call('draft-configure',{enabled:false});assert.equal((await call('draft-status')).settings.enabled,false);
  const finalRows=await readTracker(trackerPath);
  for(let i=0;i<originalRows.length;i++)for(const key of Object.keys(originalRows[i]))assert.deepEqual(finalRows[i][key],originalRows[i][key]);
  assert.equal(await digest(source),sourceHash);
});
