import crypto from 'node:crypto';
const clean = value => String(value ?? '').trim();
function dateValue(value) { if (typeof value === 'number' && Number.isFinite(value)) return new Date(Date.UTC(1899, 11, 30) + value * 86400000).toISOString().slice(0, 10); return clean(value); }
function timeValue(value) { if (typeof value === 'number' && Number.isFinite(value) && value >= 0 && value < 1) { const m = Math.round(value * 1440); return String(Math.floor(m / 60) % 24).padStart(2, '0') + ':' + String(m % 60).padStart(2, '0'); } return clean(value).slice(0, 5); }
function tagsValue(value) { return Array.isArray(value) ? value.map(clean).filter(Boolean) : clean(value).split(',').map(clean).filter(Boolean); }
function operationFor(row, order) { const phtDate = dateValue(row.scheduled_date), phtTime = timeValue(row.scheduled_time); const utcPublishAt = phtDate && phtTime ? new Date(phtDate + 'T' + phtTime + ':00+08:00').toISOString() : null; const snippet = row.snippet || {}; return Object.freeze({ order, shortId: clean(row.short_id), song: clean(row.source_song), sha256: clean(row.file_hash).toUpperCase(), youtubeId: clean(row.youtube_video_id), finalTitle: clean(row.public_title || snippet.title), description: String(row.description ?? snippet.description ?? ''), tags: Object.freeze(tagsValue(row.youtube_tags ?? snippet.tags)), category: clean(row.category), categoryId: clean(row.youtube_category_id || snippet.categoryId || '10'), privacy: 'private', publishAt: row.statusPayload?.publishAt || row.status?.publishAt || utcPublishAt, phtSchedule: (phtDate + ' ' + phtTime).trim(), utcPublishAt, channelId: clean(row.channel_id || row.youtube_channel_id) }); }
export function hashExecutionPlan(plan) { const { planHash, ...identity } = plan || {}; return crypto.createHash('sha256').update(JSON.stringify(identity)).digest('hex'); }
export function createExecutionPlan({batchId,mode,rowIds,rows}) { const approved=Object.freeze([...rowIds]); if(mode==='CANARY'&&approved.length!==2) throw new Error('CANARY requires exactly 2 explicit row IDs'); const selected=approved.map(id=>rows.find(r=>String(r.short_id)===String(id))); if(selected.some(r=>!r)) throw new Error('Execution plan contains unknown row ID'); const youtubeIds=selected.map(r=>String(r.youtube_video_id||'')); if(youtubeIds.some((id,i)=>!id||youtubeIds.indexOf(id)!==i)) throw new Error('Execution plan contains duplicate or missing YouTube IDs'); const base={executionId:crypto.randomUUID(),batchId,mode,approvedRowIds:approved,youtubeIds,operationCount:selected.length,createdAt:new Date().toISOString(),operations:Object.freeze(selected.map((row,index)=>operationFor(row,index+1)))}; return Object.freeze({...base,planHash:hashExecutionPlan(base)}); }
export function assertWriteAllowed(plan,row){ if(!plan.approvedRowIds.includes(String(row.short_id))) throw new Error(`WRITE GUARD: ${row.short_id} is not in immutable execution plan`); if(!plan.youtubeIds.includes(String(row.youtube_video_id))) throw new Error(`WRITE GUARD: YouTube relationship mismatch for ${row.short_id}`); }
export function assertExecutionPlanCurrent(plan,rows){const current=plan.approvedRowIds.map((id,index)=>{const row=rows.find(candidate=>String(candidate.short_id)===String(id));if(!row||clean(row.batch_id)!==clean(plan.batchId)||['SCHEDULED','PUBLISHED','COMPLETE','DUPLICATE','BLOCKED'].includes(clean(row.status).toUpperCase())||clean(row.schedule_eligible).toUpperCase()!=='YES')throw Error(`EXECUTION_PLAN_ROW_NOT_CURRENT:${id}`);return operationFor(row,index+1);});if(JSON.stringify(current)!==JSON.stringify(plan.operations))throw Error('EXECUTION_PLAN_TARGETS_STALE');return true;}
