import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import { linkManifestRows, buildBatchReadiness } from './existing-batch-service.mjs';
import { createExecutionPlan } from './execution-plan.mjs';
import { executeProductionRequest } from './production-entry.mjs';
import { armRealPlan, disarmRealPlan, createRealAdapter } from './youtube-adapter.mjs';

const rows = [1, 2, 3].map(i => ({ batch_id: 'BULK_03', short_id: 'S' + i, file_hash: ('A'.repeat(63) + i), source_song: 'Song ' + i, public_title: 'Title ' + i, description: 'Description ' + i, youtube_tags: 'Song ' + i + ', cover', category: 'Pop', youtube_video_id: 'Y' + i, scheduled_date: '2030-01-0' + i, scheduled_time: '17:30', timezone: 'Asia/Manila', status: 'BATCH_READY', duplicate_disposition: 'CLEARED' }));
const manifest = rows.map(row => ({ batch_id: 'BULK_03', short_id: row.short_id, sha256: row.file_hash, scheduled_date: row.scheduled_date, scheduled_time: row.scheduled_time }));
const links = linkManifestRows({ manifestRows: manifest, trackerRows: rows, batchId: 'BULK_03' });
assert.equal(links.filter(x => x.classification === 'MATCHED').length, 3);
const readiness = buildBatchReadiness({ links });
assert.equal(readiness.filter(x => x.metadata.state === 'METADATA_READY').length, 3);
assert.equal(readiness.filter(x => x.productionEligibility === 'READY').length, 3);
const basePlan = createExecutionPlan({ batchId: 'BULK_03', mode: 'PRODUCTION', rowIds: rows.map(x => x.short_id), rows });
const plan = { ...basePlan, concurrency: 1, failFast: true };
assert.equal(plan.operationCount, 3);
assert.equal(plan.operations[0].description, 'Description 1');
let writes = 0;
const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'generic-batch-'));
armRealPlan(plan);
const result = await executeProductionRequest({ request: { approved: true, executionEnvironment: 'REAL', executionPlan: plan }, rows, adapter: createRealAdapter({ enabled: true, fakeClient: { videos: { update: async payload => { writes++; return payload; } } } }), realEnabled: true, read: async () => {}, trackerUpdate: async () => {}, journalPath: path.join(dir, 'journal.json'), executionRecordPath: path.join(dir, 'execution.json'), productionLogPath: path.join(dir, 'production.log') });
assert.equal(result.ok, true);
assert.equal(writes, 3);
assert.deepEqual(result.result.journal.rows.map(row => row.state), ['COMPLETE', 'COMPLETE', 'COMPLETE']);
disarmRealPlan();
console.log('generic existing-batch and fake-client execution tests passed');
