import assert from 'node:assert/strict';import os from 'node:os';import path from 'node:path';import fs from 'node:fs/promises';import {buildProductionReview} from './production-review.mjs';import {runPlannedExecution} from './production-runner.mjs';import {progressFromJournal} from './progress-model.mjs';import {reconcileReadOnly} from './recovery-service.mjs';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ralskies-rehearsal-'));const journal=path.join(dir,'execution-journal.json');let tracker=Array.from({length:5},(_,i)=>({batch_id:'TEST',short_id:`ROW ${i+1}`,source_song:`Song ${i+1}`,youtube_video_id:`Y${i+1}`,public_title:`Title ${i+1}`,status:i<3?'BATCH_READY':'NOT_APPROVED'}));let writes=Object.fromEntries(tracker.map(r=>[r.short_id,0]));let remote={};const approved=tracker.slice(0,3);let review=buildProductionReview({batchId:'TEST',rows:tracker});assert.equal(review.plannedOperationCount,3);const plan=review.plan;
await runPlannedExecution({executionPlan:plan,rows:tracker,mode:'MOCK',channelId:'TEST',journalPath:journal,write:async r=>{writes[r.short_id]++;remote[r.youtube_video_id]={title:r.public_title,description:'D',categoryId:'10',privacyStatus:'private',publishAt:'T',channelId:'C'}},read:async()=>{},trackerUpdate:async r=>{r.status='SCHEDULED'},interruptAfterState:'APPLIED',interruptPredicate:e=>e.short_id==='ROW 2'}).catch(e=>assert.equal(e.code,'INTERRUPTED'));let persisted=JSON.parse(await fs.readFile(journal,'utf8'));assert.equal(persisted.rows.length,2);assert.equal(persisted.rows[0].state,'COMPLETE');assert.equal(persisted.rows[1].state,'APPLIED_UNVERIFIED');
// Resume a second execution over ROW 2 only after recovery reconciliation/finalization.
const row2=approved[1], expected={title:row2.public_title,description:'D',categoryId:'10',privacyStatus:'private',publishAt:'T',channelId:'C'};const rec=await reconcileReadOnly({journalRow:{youtube_video_id:'Y2',planned:expected},readRemote:async()=>remote.Y2});assert.equal(rec.state,'REMOTE_STATE_VERIFIED');row2.status='SCHEDULED';writes[row2.short_id]=1;
const remaining=approved[2];const fresh=buildProductionReview({batchId:'TEST',rows:tracker});assert.equal(fresh.plannedOperationCount,1);assert.notEqual(fresh.executionId,plan.executionId);await runPlannedExecution({executionPlan:fresh.plan,rows:tracker,mode:'MOCK',channelId:'TEST',journalPath:path.join(dir,'resume.json'),write:async r=>{writes[r.short_id]++;remote[r.youtube_video_id]={title:r.public_title}},read:async()=>{},trackerUpdate:async r=>{r.status='SCHEDULED'}});assert.equal(writes['ROW 1'],1);assert.equal(writes['ROW 2'],1);assert.equal(writes['ROW 3'],1);assert.equal(writes['ROW 4'],0);assert.equal(writes['ROW 5'],0);const mismatch=await reconcileReadOnly({journalRow:{youtube_video_id:'Y2',planned:{title:'ABC'}},readRemote:async()=>({title:'XYZ'})});assert.equal(mismatch.state,'RECONCILIATION_REQUIRED');assert.deepEqual(writes,{'ROW 1':1,'ROW 2':1,'ROW 3':1,'ROW 4':0,'ROW 5':0});assert.equal(progressFromJournal({execution_id:fresh.executionId,rows:[{short_id:'ROW 3',state:'COMPLETE'}]}).terminal,true);console.log('full mocked production rehearsal passed');




