import fs from 'node:fs/promises';
import path from 'node:path';
import {readTracker,openTracker,backupTracker,updateTrackerRows,saveTracker} from './tracker-service.mjs';
import {normalizeTags,tagsEqual} from './tag-normalizer.mjs';
import {assertWriteAllowed} from './execution-plan.mjs';
const ROOT=path.resolve(import.meta.dirname,'..'), OUT=path.join(ROOT,'outputs/ralskies-content-engine'), TRACKER=path.join(OUT,'Ralskies_Upload_Tracker.xlsx'), CONFIG=path.join(ROOT,'phase2/config.json');
const readJson=p=>fs.readFile(p,'utf8').then(JSON.parse); const date=v=>typeof v==='number'?new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10):String(v??'').trim(); const time=v=>typeof v==='number'?`${String(Math.floor(v*1440/60)%24).padStart(2,'0')}:${String(Math.round(v*1440)%60).padStart(2,'0')}`:String(v??'').trim().slice(0,5); const cat=(row,current)=>String(row.youtube_category_id||current||'10');
async function auth(c){const t=await readJson(path.resolve(ROOT,c.oauthTokenPath));if(t.expires_at&&Date.now()<t.expires_at-60000)return t.access_token;const x=(await readJson(path.resolve(ROOT,c.oauthClientPath))).installed;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:x.client_id,client_secret:x.client_secret,refresh_token:t.refresh_token,grant_type:'refresh_token'})});const n=await r.json();if(!r.ok)throw Error(n.error||'OAuth refresh failed');return n.access_token}
async function api(c,u,o={}){const r=await fetch(u,{...o,headers:{Authorization:`Bearer ${await auth(c)}`,'Content-Type':'application/json'}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(`YouTube API ${r.status}: ${b.error?.message||'failed'}`);return b} async function get(c,id){const q=new URLSearchParams({part:'id,snippet,status,processingDetails',id});return(await api(c,`https://www.googleapis.com/youtube/v3/videos?${q}`)).items?.[0]}
function check(v,row,e,c){return {videoId:v?.id,channelId:v?.snippet?.channelId,title:v?.snippet?.title,description:v?.snippet?.description,privacyStatus:v?.status?.privacyStatus,publishAt:v?.status?.publishAt,processingStatus:v?.processingDetails?.processingStatus||'unknown',passed:Boolean(v&&v.id===row.youtube_video_id&&v.snippet?.channelId===c.expectedChannelId&&v.snippet?.title===e.title&&v.snippet?.description===e.description&&tagsEqual(e.tags,v.snippet?.tags)&&v.snippet?.categoryId===e.categoryId&&v.status?.privacyStatus==='private'&&Date.parse(v.status?.publishAt||'')===Date.parse(e.publishAt))}}
export async function applyMetadataSchedule({batchId='BULK_02',offset=0,limit=14,executionPlan,durableContext}={}){if(!executionPlan)throw Error('NO_EXECUTION_PLAN: production writes disabled');if(!durableContext||durableContext.mode!=='PRODUCTION'||!durableContext.executionId||!durableContext.planHash||durableContext.rowJournalState!=='APPLYING')throw Error('DIRECT_PRODUCTION_WRITE_DISABLED'); const c=await readJson(CONFIG),rows=(await readTracker(TRACKER)).filter(r=>String(r.batch_id)===batchId&&String(r.youtube_video_id||'')).sort((a,b)=>date(a.scheduled_date).localeCompare(date(b.scheduled_date))||time(a.scheduled_time).localeCompare(time(b.scheduled_time)));if(rows.length!==14)throw Error(`Expected 14 rows, found ${rows.length}`);const backup=await backupTracker(TRACKER,`metadata-${Date.now()}`),results=[];for(const row of rows){const d=date(row.scheduled_date),t=time(row.scheduled_time),e={publishAt:new Date(`${d}T${t}:00+08:00`).toISOString(),title:String(row.public_title||''),description:String(row.description||''),tags:normalizeTags(row.youtube_tags),categoryId:cat(row,'10')},before=await get(c,row.youtube_video_id);if(!before||before.status?.privacyStatus!=='private')throw Error(`Precondition failed ${row.short_id}`);if(!check(before,row,e,c).passed){assertWriteAllowed(executionPlan,row); if(String(row.batch_id)!==String(executionPlan.batchId||executionPlan.batch_id))throw Error('BATCH_MISMATCH'); await api(c,'https://www.googleapis.com/youtube/v3/videos?part=snippet,status',{method:'PUT',body:JSON.stringify({id:row.youtube_video_id,snippet:{...before.snippet,title:e.title,description:e.description,tags:e.tags,categoryId:e.categoryId},status:{...before.status,privacyStatus:'private',publishAt:e.publishAt,selfDeclaredMadeForKids:false}})});}const actual=check(await get(c,row.youtube_video_id),row,e,c);results.push({shortId:row.short_id,youtubeVideoId:row.youtube_video_id,expected:e,actual});if(!actual.passed)throw Error(`Verification failed ${row.short_id}`);const tr=await openTracker(TRACKER);await updateTrackerRows(tr,[{short_id:row.short_id,status:'SCHEDULED',verification_state:'VERIFIED',verification_timestamp:new Date().toISOString()}]);await saveTracker(tr); if(results.length===2){ for(const canary of results){ const canaryRow=rows.find(r=>r.short_id===canary.shortId); const second=check(await get(c,canary.youtubeVideoId),canaryRow,canary.expected,c); if(!second.passed) throw Error("Canary second read-back failed"); } } } return {batchId,backup,results}}

