import { createExecutionPlan, hashExecutionPlan } from './execution-plan.mjs';
import { buildBatchReadiness, linkManifestRows, metadataReadiness, utcPublishAt, excelDate, clockTime } from './existing-batch-service.mjs';

const RECOVERY = new Set(['APPLIED','APPLIED_UNVERIFIED','VERIFYING','VERIFIED_PENDING_TRACKER','RECONCILIATION_REQUIRED']);
const COMPLETE = new Set(['SCHEDULED','PUBLISHED','COMPLETE']);
const BLOCKED = new Set(['BLOCKED','DUPLICATE','FAILED','RETIRED']);
const clean = value => String(value ?? '').trim();
function legacyLink(row) { return { manifest: row, tracker: row, classification: COMPLETE.has(clean(row.status).toUpperCase()) ? 'ALREADY_SCHEDULED' : 'MATCHED', identity: { hash: clean(row.file_hash).toUpperCase(), shortId: clean(row.short_id) }, identityMethod: 'TRACKER' }; }

export function buildProductionReview({ batchId = 'BULK_02', rows = [], recoveryRows = [], manifestRows } = {}) {
  const batch = rows.filter(row => clean(row.batch_id) === clean(batchId));
  const links = Array.isArray(manifestRows) ? linkManifestRows({ manifestRows, trackerRows: batch, batchId }) : batch.map(legacyLink);
  const recoveryIds = new Set(recoveryRows.filter(row => RECOVERY.has(clean(row.state).toUpperCase())).map(row => clean(row.short_id || row.shortId)));
  const readiness = Array.isArray(manifestRows) ? buildBatchReadiness({ links, recoveryIds }) : links.map(link => {
    const row = link.tracker, status = clean(row?.status).toUpperCase(), hasMetadataFields = row && ('description' in row || 'youtube_tags' in row || 'category' in row);
    const metadata = hasMetadataFields ? metadataReadiness(row) : { state: 'METADATA_READY', missing: [], utcPublishAt: utcPublishAt(row) };
    const ready = link.classification === 'MATCHED' && metadata.state === 'METADATA_READY' && clean(row?.youtube_video_id) && !recoveryIds.has(clean(row?.short_id)) && !BLOCKED.has(status) && !['NOT_APPROVED','UNAPPROVED','PENDING_APPROVAL'].includes(status) && !COMPLETE.has(status);
    return { ...link, metadata, recovery: recoveryIds.has(clean(row?.short_id)), productionEligibility: (BLOCKED.has(status) || ['NOT_APPROVED','UNAPPROVED','PENDING_APPROVAL'].includes(status)) ? 'BLOCKED' : ready ? 'READY' : clean(row?.youtube_video_id) ? 'BLOCKED' : 'AWAITING_PRIVATE_UPLOAD', utcPublishAt: metadata.utcPublishAt };
  });
  const executable = readiness.filter(item => item.productionEligibility === 'READY' && item.tracker).sort((a, b) => String(a.utcPublishAt || '').localeCompare(String(b.utcPublishAt || '')) || clean(a.tracker.short_id).localeCompare(clean(b.tracker.short_id)));
  const executableRows = executable.map(item => item.tracker);
  const basePlan = createExecutionPlan({ batchId, mode: 'PRODUCTION', rowIds: executableRows.map(row => clean(row.short_id)), rows: executableRows });
  const planIdentity = { ...basePlan, concurrency: 1, failFast: true };
  const plan = Object.freeze({ ...planIdentity, planHash: hashExecutionPlan(planIdentity) });
  const displayed = Array.isArray(manifestRows) ? readiness : readiness.filter(item => item.productionEligibility === 'READY');
  const outRows = displayed.map((item, index) => { const row = item.tracker || {}, meta = item.metadata || {}; return { order: item.productionEligibility === 'READY' ? executable.findIndex(x => x === item) + 1 : null, shortId: clean(row.short_id || item.identity?.shortId), song: clean(row.source_song || item.manifest?.song), hash: clean(row.file_hash || item.identity?.hash).toUpperCase(), youtubeId: clean(row.youtube_video_id), currentYoutubeTitle: clean(row.current_youtube_title || row.youtube_title || row.public_title), finalAuthoritativeTitle: clean(row.public_title), finalDescription: clean(row.description), backendTags: clean(row.youtube_tags), descriptionStatus: meta.state, tagsStatus: clean(row.youtube_tags) ? 'READY' : 'MISSING', category: clean(row.category || row.youtube_category_id), schedulePht: row.scheduled_date || row.scheduled_time ? `${String(row.scheduled_date || '')} ${String(row.scheduled_time || '')}`.trim() : '', scheduledDate: excelDate(row.scheduled_date), scheduledTime: clockTime(row.scheduled_time), publishAtUtc: item.utcPublishAt, currentStatus: clean(row.status), verification: clean(row.verification_state), productionEligibility: item.productionEligibility, classification: item.classification, missingMetadata: meta.missing || [] }; });
  const exclusions = readiness.filter(item => item.productionEligibility !== 'READY').map(item => ({ shortId: clean(item.tracker?.short_id || item.identity?.shortId), status: clean(item.tracker?.status), reason: item.recovery ? 'RECOVERY_REQUIRED' : item.classification !== 'MATCHED' ? item.classification : item.metadata?.state === 'METADATA_INCOMPLETE' ? `METADATA_INCOMPLETE:${(item.metadata.missing || []).join(',')}` : item.productionEligibility }));
  return { batchId, executionId: plan.executionId, planHash: plan.planHash, createdAt: plan.createdAt, completedCount: batch.filter(row => COMPLETE.has(clean(row.status).toUpperCase())).length, readyCount: executable.length, blockedCount: exclusions.filter(item => /^(BLOCKED|DUPLICATE|AMBIGUOUS|MISSING)/.test(String(item.reason))).length, recoveryRequiredCount: readiness.filter(item => item.recovery).length, plannedOperationCount: plan.operationCount, concurrency: 1, failFast: true, rows: outRows, readiness, exclusions, plan, manifestRowCount: manifestRows?.length ?? batch.length, matchedCount: readiness.filter(item => item.classification === 'MATCHED').length, metadataCompleteCount: readiness.filter(item => item.metadata?.state === 'METADATA_READY').length, scheduleCompleteCount: readiness.filter(item => item.metadata?.utcPublishAt).length, youtubeLinkedCount: readiness.filter(item => clean(item.tracker?.youtube_video_id)).length };
}
