import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import {executeProductionRequest} from './production-entry.mjs';
import {readTracker,openTracker,updateTrackerRows,saveTracker} from './tracker-service.mjs';
const src='outputs/ralskies-content-engine/Ralskies_Upload_Tracker.xlsx',dir=await fs.mkdtemp(path.join(os.tmpdir(),'routing-real-tracker-')),copy=path.join(dir,'validation.xlsx');await fs.copyFile(src,copy);
const candidates=(await readTracker(copy)).filter(row=>row.batch_id==='BULK_02'&&row.status==='SCHEDULED'&&row.youtube_video_id).slice(0,2);assert.equal(candidates.length,2);
let tracker=await openTracker(copy);await updateTrackerRows(tracker,candidates.map(row=>({short_id:row.short_id,status:'BATCH_READY'})));await saveTracker(tracker);
const rows=(await readTracker(copy)).filter(row=>candidates.some(candidate=>candidate.short_id===row.short_id)),plan={executionId:'TEST-REAL-ADAPTER',batchId:'BULK_02',mode:'PRODUCTION',approvedRowIds:rows.map(row=>row.short_id),youtubeIds:rows.map(row=>row.youtube_video_id),operationCount:rows.length,createdAt:new Date().toISOString(),concurrency:1,failFast:true};
let writes=0;const remote=new Set(),trackerUpdate=async row=>{const current=await openTracker(copy);await updateTrackerRows(current,[{short_id:row.short_id,status:'SCHEDULED',verification_state:'VERIFIED',verification_timestamp:new Date().toISOString()}]);await saveTracker(current);};
const result=await executeProductionRequest({request:{approved:true,executionPlan:plan},rows,write:async row=>{writes++;remote.add(row.youtube_video_id);},read:async row=>{assert.equal(remote.has(row.youtube_video_id),true);},trackerUpdate,journalPath:path.join(dir,'journal.json'),executionRecordPath:path.join(dir,'execution.json'),productionLogPath:path.join(dir,'production.log')});
assert.equal(writes,2);assert.equal(result.result.journal.rows.every(row=>row.state==='COMPLETE'),true);assert.equal((await readTracker(copy)).filter(row=>rows.some(candidate=>candidate.short_id===row.short_id)&&row.status==='SCHEDULED').length,2);
console.log(JSON.stringify({rows:rows.map(row=>row.short_id),writes,journal:'COMPLETE',productionTrackerMutations:0,realYoutubeWrites:0}));
