import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import {readTracker,openTracker,updateTrackerRows,saveTracker,backupTracker} from './tracker-service.mjs';
import {executeProductionRequest} from './production-entry.mjs';
const src=path.resolve('outputs/ralskies-content-engine/Ralskies_Upload_Tracker.xlsx'),dir=await fs.mkdtemp(path.join(os.tmpdir(),'ralskies-real-tracker-validation-')),trackerPath=path.join(dir,'tracker','validation.xlsx'),journal=path.join(dir,'journal','execution.json'),log=path.join(dir,'logs','production.log');await fs.mkdir(path.dirname(trackerPath),{recursive:true});await fs.mkdir(path.dirname(journal),{recursive:true});
const hash=async file=>crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex'),before=await hash(src);await fs.copyFile(src,trackerPath);await backupTracker(trackerPath,'validation-initial');
const candidates=(await readTracker(trackerPath)).filter(row=>row.batch_id==='BULK_02'&&row.status==='SCHEDULED'&&row.youtube_video_id).slice(0,2);assert.equal(candidates.length,2);let tracker=await openTracker(trackerPath);await updateTrackerRows(tracker,candidates.map(row=>({short_id:row.short_id,status:'BATCH_READY'})));await saveTracker(tracker);
const rows=(await readTracker(trackerPath)).filter(row=>candidates.some(candidate=>candidate.short_id===row.short_id)),plan={executionId:`TEST-REAL-${Date.now()}`,batchId:'BULK_02',mode:'PRODUCTION',approvedRowIds:rows.map(row=>row.short_id),youtubeIds:rows.map(row=>row.youtube_video_id),operationCount:rows.length,createdAt:new Date().toISOString(),concurrency:1,failFast:true};
let writes=0;const remote=new Set(),trackerUpdate=async row=>{const current=await openTracker(trackerPath);await updateTrackerRows(current,[{short_id:row.short_id,status:'SCHEDULED',verification_state:'VERIFIED',verification_timestamp:new Date().toISOString()}]);await saveTracker(current);};
const out=await executeProductionRequest({request:{approved:true,executionPlan:plan},rows,write:async row=>{writes++;remote.add(row.youtube_video_id);},read:async row=>assert.equal(remote.has(row.youtube_video_id),true),trackerUpdate,journalPath:journal,executionRecordPath:path.join(dir,'journal','execution-record.json'),productionLogPath:log});
assert.equal(out.result.journal.rows.every(row=>row.state==='COMPLETE'),true);assert.equal((await readTracker(trackerPath)).filter(row=>rows.some(candidate=>candidate.short_id===row.short_id)&&row.status==='SCHEDULED').length,2);assert.ok((await fs.readdir(path.dirname(trackerPath))).some(name=>name.includes('backup')));assert.equal(await hash(src),before);
console.log(JSON.stringify({status:'PASS',operationCount:2,mockWriteCount:writes,executionState:'COMPLETE',sourceTrackerUnchanged:true,realYoutubeWrites:0,productionTrackerMutations:0}));
