import assert from 'node:assert/strict';
import crypto from 'node:crypto'; import fs from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import {createExecutionPlan} from './execution-plan.mjs';
import {runPlannedExecution} from './production-runner.mjs';
import {executeProductionRequest} from './production-entry.mjs';
import {createMockAdapter,createRealAdapter,armRealPlan,disarmRealPlan} from './youtube-adapter.mjs';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'runner-context-'));
const rows=[{batch_id:'BULK_02',short_id:'R1',youtube_video_id:'Y1',status:'BATCH_READY',snippet:{title:'Final',description:'Desc',tags:['r'],categoryId:'10'},statusPayload:{privacyStatus:'private',publishAt:'2030-01-01T00:00:00Z'}},{batch_id:'BULK_02',short_id:'R2',youtube_video_id:'Y2',status:'BATCH_READY'}];
const base=createExecutionPlan({batchId:'BULK_02',mode:'PRODUCTION',rowIds:['R1'],rows}); const plan={...base,planHash:crypto.createHash('sha256').update(JSON.stringify(base)).digest('hex'),concurrency:1,failFast:true};
function paths(label){const j=path.join(root,label+'.journal.json');return {j,e:j+'.execution.json',l:j+'.log'};}
async function directRun({mutate, rows:runRows=rows, p=plan}={}){const q=paths(Math.random().toString(16).slice(2));const contexts=[];const writes=[];const adapter=createMockAdapter({writes});let updates=0;const result=await runPlannedExecution({executionPlan:p,rows:runRows,mode:'PRODUCTION',channelId:'TEST',write:async(op,ctx)=>{contexts.push(ctx);return adapter.applyVideoUpdate(op,ctx)},read:async()=>{},trackerUpdate:async()=>{updates++},journalPath:q.j,executionRecordPath:q.e,productionLogPath:q.l,beforeContextRead:async(_row,journalPath,executionRecordPath)=>{if(mutate)await mutate({journalPath,executionRecordPath});}});return {q,contexts,writes,updates,result};}
const ok=await directRun(); assert.equal(ok.writes.length,1);assert.equal(ok.updates,1);assert.equal(ok.result.journal.rows[0].state,'COMPLETE');const c=ok.contexts[0];const forgedAdapter=createMockAdapter({writes:[]});await assert.rejects(()=>forgedAdapter.applyVideoUpdate(rows[0],{durableState:'APPLYING',persistenceVerified:true,approved:true}),/DURABLE_CONTEXT|EXECUTION_RECORD|WRITE_DENIED/);const replayAdapter=createMockAdapter({writes:[]});await assert.rejects(()=>replayAdapter.applyVideoUpdate(rows[0],c),/DURABLE_EXECUTION_CONTEXT_REQUIRED/);await assert.rejects(()=>replayAdapter.applyVideoUpdate(rows[1],c),/DURABLE_EXECUTION_CONTEXT_REQUIRED/);const rec=JSON.parse(await fs.readFile(ok.q.e));const jr=JSON.parse(await fs.readFile(ok.q.j)).rows[0];for(const [k,v] of Object.entries({executionId:rec.executionId,planHash:rec.planHash,batchId:rec.batchId,shortId:jr.short_id,youtubeId:jr.youtube_video_id,operationIndex:0,operationCount:1,approved:true,mode:'PRODUCTION',durableState:'APPLIED',persistenceVerified:true}))assert.equal(c[k],v,k);
async function denied(mutate){let calls=0;await assert.rejects(()=>directRun({mutate}).then(x=>{calls=x.writes.length;return x;}),/DURABLE_CONTEXT_VALIDATION_FAILED|ENOENT/);assert.equal(calls,0);}
await denied(async({executionRecordPath})=>{await fs.unlink(executionRecordPath)});
await denied(async({journalPath})=>{await fs.unlink(journalPath)});
await denied(async({journalPath})=>{const x=JSON.parse(await fs.readFile(journalPath));x.rows[0].state='PRECHECK';await fs.writeFile(journalPath,JSON.stringify(x))});
for(const field of ['youtube_video_id','short_id','execution_id'])await denied(async({journalPath,executionRecordPath})=>{if(field==='execution_id'){const x=JSON.parse(await fs.readFile(executionRecordPath));x.executionId='BAD';await fs.writeFile(executionRecordPath,JSON.stringify(x));}else{const x=JSON.parse(await fs.readFile(journalPath));x.rows[0][field]=field==='youtube_video_id'?'BAD':'BAD';await fs.writeFile(journalPath,JSON.stringify(x));}});
await denied(async({executionRecordPath})=>{const x=JSON.parse(await fs.readFile(executionRecordPath));x.planHash='BAD';await fs.writeFile(executionRecordPath,JSON.stringify(x))});
await denied(async({executionRecordPath})=>{const x=JSON.parse(await fs.readFile(executionRecordPath));x.batchId='OTHER';await fs.writeFile(executionRecordPath,JSON.stringify(x))});
await denied(async({executionRecordPath})=>{const x=JSON.parse(await fs.readFile(executionRecordPath));x.approved=false;await fs.writeFile(executionRecordPath,JSON.stringify(x))});
await denied(async({executionRecordPath})=>{const x=JSON.parse(await fs.readFile(executionRecordPath));x.orderedShortIds=['R2'];await fs.writeFile(executionRecordPath,JSON.stringify(x))});
const gate=await executeProductionRequest({request:{approved:true,executionPlan:plan,executionEnvironment:'REAL'},rows:[rows[0]],realEnabled:false});assert.equal(gate.code,'REAL_PRODUCTION_EXECUTION_DISABLED');const realPlan=plan;let fakeCalls=[];const fake={videos:{update:async payload=>{fakeCalls.push(payload);return {ok:true}}}};armRealPlan(realPlan);const rr=paths('real');const realAdapter=createRealAdapter({enabled:true,fakeClient:fake});const realResult=await executeProductionRequest({request:{approved:true,executionPlan:realPlan,executionEnvironment:'REAL'},rows:[rows[0]],adapter:realAdapter,read:async()=>{},trackerUpdate:async()=>{},journalPath:rr.j,executionRecordPath:rr.e,productionLogPath:rr.l,realEnabled:true});assert.equal(realResult.ok,true);assert.equal(fakeCalls.length,1);assert.equal(fakeCalls[0].id,'Y1');assert.equal(fakeCalls[0].snippet.title,'Final');assert.equal(fakeCalls[0].snippet.description,'Desc');assert.deepEqual(fakeCalls[0].snippet.tags,['r']);assert.equal(fakeCalls[0].snippet.categoryId,'10');assert.equal(fakeCalls[0].statusPayload,undefined);assert.equal(fakeCalls[0].status.privacyStatus,'private');assert.equal(fakeCalls[0].status.publishAt,'2030-01-01T00:00:00Z');disarmRealPlan();
const twoBase=createExecutionPlan({batchId:'BULK_02',mode:'PRODUCTION',rowIds:['R1','R2'],rows});const twoPlan={...twoBase,planHash:crypto.createHash('sha256').update(JSON.stringify(twoBase)).digest('hex'),concurrency:1,failFast:true};let twoCalls=0;armRealPlan(twoPlan);const two=await executeProductionRequest({request:{approved:true,executionPlan:twoPlan,executionEnvironment:'REAL'},rows,adapter:createRealAdapter({enabled:true,fakeClient:{videos:{update:async()=>{twoCalls++;return {ok:true}}}}}),read:async()=>{},trackerUpdate:async()=>{},journalPath:paths('two').j,executionRecordPath:paths('two').e,productionLogPath:paths('two').l,realEnabled:true});assert.equal(twoCalls,2);assert.deepEqual(two.result.journal.rows.map(x=>x.state),['COMPLETE','COMPLETE']);disarmRealPlan();
console.log(JSON.stringify({status:'PASS',baseline:true,fabricatedRequestDenied:true,missingExecution:true,missingJournal:true,wrongState:true,identityTamper:['youtube_video_id','short_id','execution_id','planHash','batchId'],approvalTamper:true,operationIntegrity:true,realFakeCalls:fakeCalls.length,twoRowFakeCalls:twoCalls,liveYoutubeWrites:0,trackerMutations:0}));