import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { backupTracker, openTracker, saveTracker, updateTrackerRows } from "./tracker-service.mjs";
const BLOCKED_STATUSES = new Set(["DUPLICATE","FAILED","PRIVATE_UPLOADED","METADATA_APPLIED","SCHEDULED","PUBLISHED"]); const BLOCKED_DISPOSITION = /DUPLICATE|UNRESOLVED/i;
async function exists(filePath) { try { await fs.access(filePath); return true; } catch { return false; } }
async function sha256(filePath) { const hash = crypto.createHash("sha256"); const stream = (await import("node:fs")).createReadStream(filePath); for await (const chunk of stream) hash.update(chunk); return hash.digest("hex").toUpperCase(); }
function transactionId() { return `${new Date().toISOString().replace(/[-:.TZ]/g, "").slice(0, 14)}-${crypto.randomBytes(4).toString("hex")}`; }
export async function loadPreparation(transactionPath) { const data = JSON.parse(await fs.readFile(transactionPath, "utf8")); if (data.state !== "COMPLETE") throw new Error("Batch preparation transaction is not COMPLETE."); return data; }
function assertTestIsolation(environment, ...pathsToCheck) { if (environment !== "TEST") return; for (const candidate of pathsToCheck) { const value = String(candidate || "").toUpperCase(); if (value.includes("G:\\RS_BULK") || value.includes("OUTPUTS\\RALSKIES-CONTENT-ENGINE\\RALSKIES_UPLOAD_TRACKER")) throw new Error(`TEST isolation rejected production path: ${candidate}`); } }
export function reconcileBatchState(batch, trackerRows) {
  const ids = new Set((batch.videos || []).map((video) => String(video.shortId))); const rows = trackerRows.filter((row) => ids.has(String(row.short_id))); const linked = rows.filter((row) => String(row.youtube_video_id || "").trim()).length; const staged = rows.filter((row) => String(row.current_path || "").trim()).length; const published = rows.filter((row) => String(row.status || "").toUpperCase() === "PUBLISHED").length; const scheduled = rows.filter((row) => String(row.status || "").toUpperCase() === "SCHEDULED").length;
  const state = rows.length && linked === rows.length && staged === rows.length ? (published === rows.length ? "PUBLISHED" : "SCHEDULED") : staged ? (scheduled ? "SCHEDULED" : "STAGED") : "PREPARED";
  return { state, totalRows: rows.length, linkedYouTubeIds: linked, stagedRows: staged, scheduledRows: scheduled, publishedRows: published };
}
export async function previewBatch({ transactionPath, trackerPath, batchId = "BULK_01", environment = "PRODUCTION" }) {
  assertTestIsolation(environment, transactionPath, trackerPath);
  const preparation = await loadPreparation(transactionPath); const batch = preparation.batches?.find((candidate) => candidate.batchId === batchId); if (!batch) throw new Error(`Batch ${batchId} is not present in the preparation transaction.`);
  const tracker = await openTracker(trackerPath); const records = new Map(); for (const record of tracker.records) { const key = String(record.data.short_id); if (!records.has(key)) records.set(key, []); records.get(key).push(record.data); } const seen = new Set(); const operations = []; const excluded = []; const errors = []; const warnings = [];
  for (const video of batch.videos || []) { const candidates = records.get(String(video.shortId)) || []; const row = candidates.find((candidate) => String(candidate.current_path || "").trim() === String(video.destination)) || candidates.find((candidate) => String(candidate.schedule_eligible).toUpperCase() === "YES") || candidates[0]; const result = { shortId: video.shortId, source: video.source, destination: video.destination, expectedHash: String(video.sha256).toUpperCase(), checks: {} };
    const status = String(row?.status || "").toUpperCase(); const existingPath = String(row?.current_path || "").trim();
    if (row && (String(row.youtube_video_id || "").trim() || BLOCKED_STATUSES.has(status) || existingPath)) { excluded.push({ shortId: video.shortId, reason: String(row.youtube_video_id || "").trim() ? "ALREADY_UPLOADED_OR_LINKED" : existingPath ? "ALREADY_STAGED" : `STATUS_${status}`, status, currentPath: existingPath, youtubeVideoId: String(row.youtube_video_id || "") }); continue; }
    result.checks.sourceExists = await exists(result.source); result.checks.trackerRowFound = Boolean(row); result.checks.eligible = Boolean(row && String(row.schedule_eligible).toUpperCase() === "YES"); result.checks.statusAllowed = Boolean(row && !BLOCKED_STATUSES.has(String(row.status).toUpperCase())); result.checks.dispositionAllowed = Boolean(row && !BLOCKED_DISPOSITION.test(String(row.duplicate_disposition || ""))); result.checks.notUploaded = Boolean(row && !String(row.youtube_video_id || "").trim()); result.checks.notDestinationCollision = !await exists(result.destination); result.checks.noHashCollision = !seen.has(result.expectedHash);
    if (row) Object.assign(result, { scheduledDate: row.scheduled_date, scheduledTime: row.scheduled_time, timezone: row.timezone, song: row.source_song, artist: row.artist_or_fandom, fandom: row.artist_or_fandom, category: row.category, finalPublicTitle: row.public_title, description: row.description, hashtags: row.hashtags, youtubeTags: row.youtube_tags, relatedVideoId: row.related_video_id });
    if (result.checks.sourceExists) { result.actualHash = await sha256(result.source); result.checks.hashMatches = result.actualHash === result.expectedHash; } else result.checks.hashMatches = false; seen.add(result.expectedHash); for (const [name, passed] of Object.entries(result.checks)) if (!passed) errors.push(`${video.shortId}: ${name}`); operations.push(result); }
  return { batchId, preparationState: preparation.state, stagingState: errors.length ? "BLOCKED" : operations.length ? "NOT_STAGED" : "NO_ELIGIBLE_ITEMS", manifestState: "NOT_GENERATED", operations, excluded, valid: operations.length - errors.length, warnings, errors, transactionId: transactionId() };
}
async function writeManifest(batchDir, batchId, operations) {
  const { SpreadsheetFile, Workbook } = await import("../outputs/ralskies-content-engine/work/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs");
  const workbook = Workbook.create(); const sheet = workbook.worksheets.add("Manifest");
  const headers = ["batch_id","scheduled_date","scheduled_time","timezone","short_id","sha256","original_filename","original_path","staged_filename","staged_path","song","artist","fandom","category","final_public_title","description","hashtags","youtube_tags","related_video_id","status"];
  const rows = operations.map((operation) => [batchId, operation.scheduledDate, operation.scheduledTime, operation.timezone, operation.shortId, operation.expectedHash, path.basename(operation.source), operation.source, path.basename(operation.destination), operation.destination, operation.song, operation.artist, operation.fandom, operation.category, operation.finalPublicTitle, operation.description, operation.hashtags, operation.youtubeTags, operation.relatedVideoId, "BATCH_READY"]);
  sheet.getRangeByIndexes(0, 0, rows.length + 1, headers.length).values = [headers, ...rows]; sheet.freezePanes.freezeRows(1); sheet.getRange(`A1:T1`).format = { fill: "#14243C", font: { bold: true, color: "#FFFFFF" } }; sheet.getRange(`A:T`).format.columnWidth = 24;
  const output = await SpreadsheetFile.exportXlsx(workbook); const manifestPath = path.join(batchDir, "BULK_MANIFEST.xlsx"); await output.save(manifestPath); return manifestPath;
}
export async function applyBatch({ preview, trackerPath, transactionPath, confirmation, environment = "PRODUCTION" }) {
  assertTestIsolation(environment, trackerPath, transactionPath, ...(preview?.operations || []).flatMap((operation) => [operation.source, operation.destination]));
  if (!preview || preview.stagingState !== "NOT_STAGED" || preview.errors.length) throw new Error("A successful preview is required before staging."); if (confirmation !== `Stage ${preview.batchId}?`) throw new Error(`Explicit confirmation required: Stage ${preview.batchId}?`); const tx = { version: 1, transactionId: preview.transactionId, batchId: preview.batchId, state: "STARTED", mode: "COPY", operations: preview.operations, trackerPath, startedAt: new Date().toISOString() }; tx.backupPath = await backupTracker(trackerPath, tx.transactionId);
  try { tx.state = "STAGING"; for (const operation of tx.operations) { await fs.mkdir(path.dirname(operation.destination), { recursive: true }); await fs.copyFile(operation.source, operation.destination, fs.constants.COPYFILE_EXCL); operation.stagedHash = await sha256(operation.destination); if (operation.stagedHash !== operation.expectedHash) throw new Error(`${operation.shortId}: staged hash mismatch.`); } tx.state = "FILES_VERIFIED";
    tx.manifestPath = await writeManifest(path.dirname(tx.operations[0].destination), tx.batchId, tx.operations); const updates = tx.operations.map((operation) => ({ short_id: operation.shortId, batch_id: tx.batchId, original_filename: path.basename(operation.source), original_path: operation.source, current_filename: path.basename(operation.destination), current_path: operation.destination, file_hash: operation.expectedHash, status: "BATCH_READY" })); const tracker = await openTracker(trackerPath); await updateTrackerRows(tracker, updates); await saveTracker(tracker); tx.state = "COMPLETE"; await fs.writeFile(`${transactionPath}.${tx.transactionId}.json`, JSON.stringify(tx, null, 2)); return tx;
  } catch (error) { tx.state = "FAILED"; tx.error = error.message; await fs.writeFile(`${transactionPath}.${tx.transactionId}.json`, JSON.stringify(tx, null, 2)); throw error; }
}

export async function rollbackBatch({ transactionFile, trackerPath, environment = "PRODUCTION" }) {
  assertTestIsolation(environment, transactionFile, trackerPath);
  const tx = JSON.parse(await fs.readFile(transactionFile, "utf8")); if (tx.state !== "COMPLETE") throw new Error("Only a completed staging transaction can be rolled back."); const tracker = await openTracker(trackerPath);
  for (const operation of tx.operations || []) { const row = tracker.records.find((candidate) => String(candidate.data.short_id) === String(operation.shortId)); if (row && String(row.data.youtube_video_id || "").trim()) throw new Error(`Rollback blocked: ${operation.shortId} has a YouTube video ID.`); }
  for (const operation of tx.operations || []) if (await exists(operation.destination)) await fs.unlink(operation.destination); if (tx.manifestPath && await exists(tx.manifestPath)) await fs.unlink(tx.manifestPath); if (!(await exists(tx.backupPath))) throw new Error("Rollback backup is missing; tracker was left unchanged."); await fs.copyFile(tx.backupPath, trackerPath); return { transactionId: tx.transactionId, state: "ROLLED_BACK", removed: (tx.operations || []).length, trackerRestored: true, originalsUntouched: true };
}
