import fs from "node:fs/promises";
import { isProtected } from "./schedule-calendar.mjs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { readTracker } from "./tracker-service.mjs";
import { loadPreparation } from "./staging-service.mjs";
import { matchPrivateVideos } from "./youtube-matching.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const CONFIG_PATH = path.join(ROOT, "phase2", "config.json");
async function readJson(file, optional = false) { try { return JSON.parse(await fs.readFile(file, "utf8")); } catch (error) { if (optional && error.code === "ENOENT") return null; throw error; } }
async function config() { const value = await readJson(CONFIG_PATH); return { ...value, oauthClientPath: path.resolve(ROOT, value.oauthClientPath), oauthTokenPath: path.resolve(ROOT, value.oauthTokenPath), trackerPath: path.join(ROOT, "outputs/ralskies-content-engine/Ralskies_Upload_Tracker.xlsx") }; }
function excelDate(value) { if (typeof value === "number" && Number.isFinite(value)) { const d = new Date(Date.UTC(1899, 11, 30) + value * 86400000); return d.toISOString().slice(0, 10); } return String(value ?? "").trim(); }
function clockTime(value) { if (typeof value === "number" && Number.isFinite(value) && value >= 0 && value < 1) { const minutes = Math.round(value * 1440); return `${String(Math.floor(minutes / 60) % 24).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; } return String(value ?? "").trim().slice(0, 5); }
async function clientAccessToken(cfg) { const token = await readJson(cfg.oauthTokenPath); if (token.expires_at && Date.now() < token.expires_at - 60000) return token.access_token; const clientFile = await readJson(cfg.oauthClientPath); const client = clientFile.installed || clientFile.web; const body = new URLSearchParams({ client_id: client.client_id, client_secret: client.client_secret, refresh_token: token.refresh_token, grant_type: "refresh_token" }); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", body }); const fresh = await response.json(); if (!response.ok) throw new Error(`OAuth refresh failed (${response.status}): ${fresh.error || "unknown error"}`); await fs.writeFile(cfg.oauthTokenPath, JSON.stringify({ ...token, access_token: fresh.access_token, expires_at: Date.now() + fresh.expires_in * 1000, scope: fresh.scope || token.scope, token_type: fresh.token_type || token.token_type }, null, 2)); return fresh.access_token; }
async function api(cfg, endpoint) { const response = await fetch(endpoint, { headers: { Authorization: `Bearer ${await clientAccessToken(cfg)}` } }); const text = await response.text(); let body; try { body = JSON.parse(text); } catch { body = { error: { message: text.slice(0, 300) } }; } if (!response.ok) throw new Error(`YouTube API ${response.status}: ${body.error?.message || "request failed"}`); return body; }
async function verifyChannel(cfg) { const data = await api(cfg, "https://www.googleapis.com/youtube/v3/channels?part=id%2Csnippet%2CcontentDetails&mine=true"); const channel = data.items?.[0]; if (!channel) throw new Error("Authenticated account has no YouTube channel."); if (channel.id !== cfg.expectedChannelId || channel.snippet?.title !== cfg.expectedChannelTitle) throw new Error(`CHANNEL MISMATCH: expected ${cfg.expectedChannelTitle} (${cfg.expectedChannelId}), got ${channel.snippet?.title || "unknown"} (${channel.id || "unknown"}).`); return channel; }
async function privateVideos(cfg, channel) { const playlistId = channel.contentDetails?.relatedPlaylists?.uploads; if (!playlistId) return []; const ids = []; let pageToken = ""; do { const query = new URLSearchParams({ part: "contentDetails", playlistId, maxResults: "50" }); if (pageToken) query.set("pageToken", pageToken); const page = await api(cfg, `https://www.googleapis.com/youtube/v3/playlistItems?${query}`); ids.push(...(page.items || []).map((item) => item.contentDetails?.videoId).filter(Boolean)); pageToken = page.nextPageToken || ""; } while (pageToken); const videos = []; for (let offset = 0; offset < ids.length; offset += 50) { const query = new URLSearchParams({ part: "id,snippet,status", id: ids.slice(offset, offset + 50).join(",") }); const page = await api(cfg, `https://www.googleapis.com/youtube/v3/videos?${query}`); videos.push(...(page.items || []).filter((item) => item.status?.privacyStatus === "private").map((item) => ({ id: item.id, title: item.snippet?.title || "", privacyStatus: item.status?.privacyStatus }))); } return videos; }
export async function discoverPrivateBatch({ batchId = "BULK_02" } = {}) { const cfg = await config(); const batch = /^INTAKE-/.test(batchId) ? { videos: (await readTracker(cfg.trackerPath)).filter(row => String(row.batch_id) === batchId).map(row => ({ shortId: row.short_id })) } : (await loadPreparation(path.join(ROOT, "outputs/ralskies-content-engine/bulk_preparation_transaction.json"))).batches?.find(candidate => candidate.batchId === batchId); if (!batch) throw new Error(`Batch ${batchId} is not present in preparation data.`); const rows = await readTracker(cfg.trackerPath); const ids = new Set((batch.videos || []).map((video) => video.shortId)); const selectedRows = rows.filter((row) => ids.has(String(row.short_id)) && String(row.schedule_eligible).toUpperCase() === "YES" && !String(row.youtube_video_id || "").trim() && !/DUPLICATE|UNRESOLVED/i.test(String(row.duplicate_disposition || "")) && !["DUPLICATE", "BLOCKED", "UNRESOLVED", "RECONCILIATION_REQUIRED", "PUBLISHED", "SCHEDULED"].includes(String(row.status || "").toUpperCase())); const channel = await verifyChannel(cfg); const videos = await privateVideos(cfg, channel); const match = matchPrivateVideos(videos, selectedRows); return { batchId, channel: { id: channel.id, title: channel.snippet?.title }, expected: /^INTAKE-/.test(batchId) ? selectedRows.length : batch.videos?.length || 0, selectedRows: selectedRows.length, ...match }; }

export async function verifyConfirmedBatch({ batchId = "BULK_02" } = {}) { const cfg = await config(); const batch = /^INTAKE-/.test(batchId) ? { videos: (await readTracker(cfg.trackerPath)).filter(row => String(row.batch_id) === batchId).map(row => ({ shortId: row.short_id })) } : (await loadPreparation(path.join(ROOT, "outputs/ralskies-content-engine/bulk_preparation_transaction.json"))).batches?.find(candidate => candidate.batchId === batchId); if (!batch) throw new Error(`Batch ${batchId} is not present in preparation data.`); const rows = await readTracker(cfg.trackerPath); const ids = new Set((batch.videos || []).map((video) => video.shortId)); const selectedRows = rows.filter((row) => ids.has(String(row.short_id)) && String(row.youtube_video_id || "").trim()); const channel = await verifyChannel(cfg); const videos = await privateVideos(cfg, channel); const result = matchPrivateVideos(videos, selectedRows); const checks = selectedRows.map((row) => { const video = videos.find((candidate) => String(candidate.id) === String(row.youtube_video_id)); return { shortId: row.short_id, youtubeVideoId: row.youtube_video_id, exists: Boolean(video), channelVerified: true, private: Boolean(video), titleResolvesToHash: Boolean(video && String(row.file_hash).toUpperCase() === String((video.title || "").trim().replace(/\.mp4$/i, "").toUpperCase())) }; }); if (checks.some((check) => !check.exists || !check.private || !check.titleResolvesToHash)) throw new Error("Post-confirmation verification failed for one or more tracker relationships."); return { batchId, channel: { id: channel.id, title: channel.snippet?.title }, expected: selectedRows.length, verified: checks.length, checks, match: result }; }

export async function previewMetadataSchedule({ batchId = "BULK_02" } = {}) { const cfg = await config(); const rows = await readTracker(cfg.trackerPath); const selected = rows.filter((row) => String(row.batch_id) === batchId && String(row.youtube_video_id || "").trim()); if (!selected.length) throw new Error(`No confirmed tracker matches found for ${batchId}.`); const channel = await verifyChannel(cfg); const ids = selected.map((row) => row.youtube_video_id); const videos = []; for (let offset = 0; offset < ids.length; offset += 50) { const query = new URLSearchParams({ part: "id,snippet,status,contentDetails", id: ids.slice(offset, offset + 50).join(",") }); const page = await api(cfg, `https://www.googleapis.com/youtube/v3/videos?${query}`); videos.push(...(page.items || [])); } const now = Date.now(); const previews = selected.map((row) => { const video = videos.find((candidate) => candidate.id === row.youtube_video_id); const date = excelDate(row.scheduled_date); const time = clockTime(row.scheduled_time); const publishAt = date && time ? new Date(`${date}T${time}:00+08:00`) : null; const validTime = /^([01]\d|2[0-3]):[0-5]\d$/.test(time); const protectedTime = isProtected(time); return { shortId: row.short_id, sha256: row.file_hash, youtubeVideoId: row.youtube_video_id, currentTitle: video?.snippet?.title || "", finalTitle: row.public_title || "", currentDescription: video?.snippet?.description || "", finalDescription: row.description || "", backendTags: row.youtube_tags || "", category: row.category || "", currentVisibility: video?.status?.privacyStatus || "unknown", scheduledDate: date, scheduledTime: time, timezone: row.timezone || cfg.timezone, apiUtc: publishAt && !Number.isNaN(publishAt.valueOf()) ? publishAt.toISOString() : null, relatedVideoId: row.related_video_id || "", relatedVideoAction: row.related_video_id ? "MANUAL RELATED VIDEO" : "", checks: { videoExists: Boolean(video), private: video?.status?.privacyStatus === "private", futureDate: Boolean(publishAt && publishAt.valueOf() > now), validTime, protectedWindowClear: !protectedTime, metadataPresent: Boolean(row.public_title && row.description), titleWillChange: Boolean(video && row.public_title && video.snippet.title !== row.public_title) } }; }); const blockers = previews.flatMap((preview) => Object.entries(preview.checks).filter(([, passed]) => !passed).map(([name]) => `${preview.shortId}: ${name}`)); return { batchId, channel: { id: channel.id, title: channel.snippet?.title }, expected: previews.length, ready: previews.length - blockers.length, warnings: previews.filter((preview) => preview.relatedVideoId).length ? ["Related Video requires manual Studio action."] : [], blockers, manualRelatedVideoCount: previews.filter((preview) => preview.relatedVideoId).length, previews, state: blockers.length ? "BLOCKED" : "READY_FOR_METADATA" }; }
