import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { readTracker } from "./tracker-service.mjs";
import { loadPreparation } from "./staging-service.mjs";
import { matchPrivateVideos } from "./youtube-matching.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const CONFIG_PATH = path.join(ROOT, "phase2", "config.json");
async function readJson(file, optional = false) { try { return JSON.parse(await fs.readFile(file, "utf8")); } catch (error) { if (optional && error.code === "ENOENT") return null; throw error; } }
async function config() { const value = await readJson(CONFIG_PATH); return { ...value, oauthClientPath: path.resolve(ROOT, value.oauthClientPath), oauthTokenPath: path.resolve(ROOT, value.oauthTokenPath), trackerPath: path.resolve(ROOT, value.trackerPath) }; }
async function clientAccessToken(cfg) { const token = await readJson(cfg.oauthTokenPath); if (token.expires_at && Date.now() < token.expires_at - 60000) return token.access_token; const clientFile = await readJson(cfg.oauthClientPath); const client = clientFile.installed || clientFile.web; const body = new URLSearchParams({ client_id: client.client_id, client_secret: client.client_secret, refresh_token: token.refresh_token, grant_type: "refresh_token" }); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", body }); const fresh = await response.json(); if (!response.ok) throw new Error(`OAuth refresh failed (${response.status}): ${fresh.error || "unknown error"}`); await fs.writeFile(cfg.oauthTokenPath, JSON.stringify({ ...token, access_token: fresh.access_token, expires_at: Date.now() + fresh.expires_in * 1000, scope: fresh.scope || token.scope, token_type: fresh.token_type || token.token_type }, null, 2)); return fresh.access_token; }
async function api(cfg, endpoint) { const response = await fetch(endpoint, { headers: { Authorization: `Bearer ${await clientAccessToken(cfg)}` } }); const text = await response.text(); let body; try { body = JSON.parse(text); } catch { body = { error: { message: text.slice(0, 300) } }; } if (!response.ok) throw new Error(`YouTube API ${response.status}: ${body.error?.message || "request failed"}`); return body; }
async function verifyChannel(cfg) { const data = await api(cfg, "https://www.googleapis.com/youtube/v3/channels?part=id%2Csnippet%2CcontentDetails&mine=true"); const channel = data.items?.[0]; if (!channel) throw new Error("Authenticated account has no YouTube channel."); if (channel.id !== cfg.expectedChannelId || channel.snippet?.title !== cfg.expectedChannelTitle) throw new Error(`CHANNEL MISMATCH: expected ${cfg.expectedChannelTitle} (${cfg.expectedChannelId}), got ${channel.snippet?.title || "unknown"} (${channel.id || "unknown"}).`); return channel; }
async function privateVideos(cfg, channel) { const playlistId = channel.contentDetails?.relatedPlaylists?.uploads; if (!playlistId) return []; const ids = []; let pageToken = ""; do { const query = new URLSearchParams({ part: "contentDetails", playlistId, maxResults: "50" }); if (pageToken) query.set("pageToken", pageToken); const page = await api(cfg, `https://www.googleapis.com/youtube/v3/playlistItems?${query}`); ids.push(...(page.items || []).map((item) => item.contentDetails?.videoId).filter(Boolean)); pageToken = page.nextPageToken || ""; } while (pageToken); const videos = []; for (let offset = 0; offset < ids.length; offset += 50) { const query = new URLSearchParams({ part: "id,snippet,status", id: ids.slice(offset, offset + 50).join(",") }); const page = await api(cfg, `https://www.googleapis.com/youtube/v3/videos?${query}`); videos.push(...(page.items || []).filter((item) => item.status?.privacyStatus === "private").map((item) => ({ id: item.id, title: item.snippet?.title || "", privacyStatus: item.status?.privacyStatus }))); } return videos; }
export async function discoverPrivateBatch({ batchId = "BULK_02" } = {}) { const cfg = await config(); const preparation = await loadPreparation(path.join(ROOT, "outputs/ralskies-content-engine/bulk_preparation_transaction.json")); const batch = preparation.batches?.find((candidate) => candidate.batchId === batchId); if (!batch) throw new Error(`Batch ${batchId} is not present in preparation data.`); const rows = await readTracker(cfg.trackerPath); const ids = new Set((batch.videos || []).map((video) => video.shortId)); const selectedRows = rows.filter((row) => ids.has(String(row.short_id)) && String(row.schedule_eligible).toUpperCase() === "YES" && !String(row.youtube_video_id || "").trim() && !["DUPLICATE", "BLOCKED", "PUBLISHED", "SCHEDULED"].includes(String(row.status || "").toUpperCase())); const channel = await verifyChannel(cfg); const videos = await privateVideos(cfg, channel); const match = matchPrivateVideos(videos, selectedRows); return { batchId, channel: { id: channel.id, title: channel.snippet?.title }, expected: batch.videos?.length || 0, selectedRows: selectedRows.length, ...match }; }

