let armed=null;const consumedContexts=new WeakSet();
import {assertDurableWrite} from './production-durability.mjs';
function dateValue(v){return typeof v==='number'?new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10):String(v??'').trim();}
function timeValue(v){return typeof v==='number'?String(Math.floor(v*1440/60)%24).padStart(2,'0')+':'+String(Math.round(v*1440)%60).padStart(2,'0'):String(v??'').trim().slice(0,5);}
function payloadFor(op){const snippet=op.snippet||{title:String(op.public_title||''),description:String(op.description||''),tags:String(op.youtube_tags||'').split(',').map(x=>x.trim()).filter(Boolean),categoryId:String(op.youtube_category_id||'10')};const d=dateValue(op.scheduled_date),t=timeValue(op.scheduled_time);const publishAt=op.publishAt||((d&&t)?new Date(d+'T'+t+':00+08:00').toISOString():undefined);const status=op.statusPayload||op.status;if(status&&typeof status==='object')return {snippet,status};return {snippet,status:{privacyStatus:'private',publishAt,selfDeclaredMadeForKids:false}};}
export function armRealPlan(plan){armed={enabled:true,executionId:plan.executionId,planHash:plan.planHash,batchId:plan.batchId,operationCount:plan.operationCount,orderedYoutubeIds:[...(plan.youtubeIds||[])]};return {...armed};}
export function disarmRealPlan(){armed=null;}
export function createMockAdapter({writes}={}){return {async applyVideoUpdate(op,durableContext){if(!durableContext||consumedContexts.has(durableContext)||durableContext.durableState!=='APPLYING'||durableContext.persistenceVerified!==true||durableContext.approved!==true)throw Error('DURABLE_EXECUTION_CONTEXT_REQUIRED');await assertDurableWrite({record:durableContext.executionRecord,rowJournal:durableContext.rowJournal,executionId:durableContext.executionId,row:{short_id:durableContext.shortId,youtube_video_id:durableContext.youtubeId},plan:durableContext.plan});writes?.push(op.youtube_video_id||op.youtubeId);consumedContexts.add(durableContext);durableContext.durableState='APPLIED';return {mock:true,youtubeId:op.youtube_video_id||op.youtubeId}},async readVideo(){return {ok:true}}};}
export function createRealAdapter({fakeClient,enabled=false}={}){return {async applyVideoUpdate(op,durableContext){if(!enabled||!armed?.enabled)throw Error('REAL_PRODUCTION_EXECUTION_DISABLED');if(!durableContext)throw Error('DURABLE_EXECUTION_CONTEXT_REQUIRED');const ctx=durableContext;if(ctx.executionId!==armed.executionId||ctx.planHash!==armed.planHash||ctx.batchId!==armed.batchId||ctx.approved!==true)throw Error('WRITE_DENIED_PLAN_NOT_ARMED');await assertDurableWrite({record:ctx.executionRecord,rowJournal:ctx.rowJournal,executionId:ctx.executionId,row:{short_id:ctx.shortId,youtube_video_id:ctx.youtubeId},plan:ctx.plan});if(!fakeClient?.videos?.update)throw Error('REAL_ADAPTER_CLIENT_REQUIRED');const payload=payloadFor(op);const result=await fakeClient.videos.update({id:op.youtubeId||op.youtube_video_id,snippet:payload.snippet,status:payload.status});consumedContexts.add(durableContext);durableContext.durableState='APPLIED';return result;}};}
