const state={inventory:null,view:'dashboard'}; const el=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function dashboard(){const d=state.inventory?.dashboard||{},f=state.inventory?.files||[],u=new Set(f.map(x=>x.hash)).size;return `<div class="grid"><div class="card"><div class="label">Channel</div><div class="value" style="font-size:20px">Ralskies</div><div class="hint">UCIt8eA8uvrDVbpta0pgIc5Q</div></div><div class="card"><div class="label">Current inventory</div><div class="value">${d['MP4 files']??f.length}</div><div class="hint">${u} unique hashes</div></div><div class="card"><div class="label">Upload API</div><div class="value status" style="font-size:19px">Private only</div><div class="hint">Compliance audit required</div></div><div class="card"><div class="label">Schedule</div><div class="value">${d['Draft auto/day']??2}/day</div><div class="hint">17:30 · 22:30 PHT</div></div></div><div class="section"><div class="panel callout"><div><strong>Local-first control layer</strong><span>Backend services remain deterministic. YouTube actions are gated while Dry Run is enabled.</span></div><span class="pill">● CONNECTED · RALSKIES</span></div></div><div class="section"><div class="section-title"><h2>Inventory status</h2><span class="pill">Read-only snapshot</span></div><div class="grid"><div class="card"><div class="label">Cleared / ready</div><div class="value">${d['Batch-ready Shorts']??'—'}</div><div class="hint">Tracker source of truth</div></div><div class="card"><div class="label">Review / blocked</div><div class="value">${d['Blocked/review Shorts']??d['Review items']??'—'}</div><div class="hint">Duplicates and unresolved stay protected</div></div><div class="card"><div class="label">Protected window</div><div class="value" style="font-size:20px">20:00–21:00</div><div class="hint">Asia/Manila · manual</div></div><div class="card"><div class="label">Mode</div><div class="value" style="font-size:20px">Approval</div><div class="hint">No production changes</div></div></div></div><div class="section"><div class="section-title"><h2>Quick actions</h2></div><div class="header-actions"><button class="primary" data-action="add">＋ Add Videos</button><button class="ghost" data-action="scan">↻ Scan Folder</button><button class="ghost" data-action="schedule">▦ Preview Schedule</button><button class="ghost" data-action="batch">▤ Create Batches</button><button class="ghost" data-action="youtube">◉ Verify YouTube</button></div></div>`}
function videos(){const rows=(state.inventory?.files||[]).slice(0,80);return `<div class="panel"><div class="section-title"><h2>Video library</h2><span class="pill">${state.inventory?.files?.length||0} MP4 files · SHA-256 indexed</span></div><table><thead><tr><th>File</th><th>SHA-256</th><th>Size</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td style="font-family:monospace;color:#9da9c5">${x.hash.slice(0,16)}…</td><td>${(x.size/1048576).toFixed(1)} MB</td><td><span class="pill">${x.status}</span></td></tr>`).join('')}</tbody></table></div>`}
function calendar(){const rows=state.calendar||[];return `<div class="panel"><div class="section-title"><h2>Schedule calendar</h2><span class="pill">Asia/Manila · persisted draft</span></div>${rows.length?`<table><thead><tr><th>Date / time</th><th>File</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.scheduled_time||'Unscheduled')}</td><td>${esc(x.file||x.short_id||'')}</td><td><span class="pill">${esc(x.status||'UPLOAD_READY')}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No generated schedule is stored yet. Use Preview Schedule in Dry Run mode.</div>'}</div>`}
function generic(t,b){return `<div class="panel"><div class="section-title"><h2>${t}</h2><span class="pill">Phase A · dry run</span></div><div class="empty">${b}</div></div>`}
function render(){const t=state.view[0].toUpperCase()+state.view.slice(1).replace('-', ' ');el('#view-title').textContent=t;el('#view').innerHTML=state.view==='dashboard'?dashboard():state.view==='videos'?videos():state.view==='calendar'?calendar():generic(t,state.view==='youtube'?'OAuth is connected to Ralskies; production uploads remain disabled by API restriction.':'This screen is scaffolded for the next phase. Existing backend logic remains the source of truth.')}
async function load(){state.inventory=await window.ralskies.inventory();state.calendar=await window.ralskies.calendar();render()}
async function load(){state.inventory=await window.ralskies.inventory();render()}
el('#nav').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;render()});
document.addEventListener('click',async e=>{const action=e.target.closest('[data-action]')?.dataset.action||(e.target.id==='scan'?'scan':e.target.id==='add'?'add':null);if(action==='scan'){await load();return}if(action==='add'){const folder=await window.ralskies.chooseFolder();if(folder)alert(`Selected folder:\n${folder}\n\nDry Run: files will be indexed after the import service is enabled.`);return}if(action)alert(`${action} preview is available in Dry Run mode. No changes were made.`)}); load().catch(err=>{el('#view').innerHTML=generic('Inventory unavailable',esc(err.message))});
