/* Local draft and calendar views. All writes go through the isolated preload bridge. */
window.DraftViews = {
  date(value) { return typeof value==='number'?new Date(Date.UTC(1899,11,30)+value*86400000).toISOString().slice(0,10):String(value??''); },
  time(value) { if(typeof value!=='number')return String(value??'');const minutes=Math.round(value*1440);return String(Math.floor(minutes/60)%24).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0'); },
  drafts(state, esc) {
    const data=state.drafts||{},config=data.settings||{},rows=data.rows||[];
    return `<section class="panel"><div class="section-title"><div><h2>New Shorts</h2><p class="subtle">Add new MP4s whenever you have them. Set the song and performance type, plan the next two weeks, then approve metadata and publish.</p></div><span class="pill">${config.enabled?'Watching folder':'Watcher stopped'}</span></div>
      <dl class="details"><dt>Draft folder</dt><dd>${esc(config.draftFolder||'Choose a folder to begin')}</dd><dt>Hashed folder</dt><dd>${esc(config.hashedFolder||'')}</dd></dl>
      <div class="button-row"><button class="ghost" data-draft-folder>Choose Draft Folder</button><button class="ghost" data-llm-settings>LM Studio Connection</button><button class="ghost" data-analytics-open>Weekly Analytics / Timing Evidence</button><button class="ghost" data-draft-preview ${config.draftFolder?'':'disabled'}>Preview Intake</button><button class="primary" data-draft-scan ${config.draftFolder?'':'disabled'}>Intake Now</button><button class="ghost" data-draft-watch ${config.draftFolder?'':'disabled'}>${config.enabled?'Stop Watching':'Watch Folder'}</button></div>
      <p class="subtle section">Watching runs every 15 seconds while this app is open. Intake keeps your originals and creates verified copies in the hashed subfolder. Use the batch upload controls when ready to upload privately.</p>
      ${data.lastScan?`<p class="subtle">Last scan: ${esc(data.lastScan.at)} · ${data.lastScan.added?.length||0} added · ${data.lastScan.waiting?.length||0} still copying · ${data.lastScan.exceptions?.length||0} exceptions</p>`:''}</section>
      ${data.exceptions?.length?`<section class="panel section"><h2>Intake exceptions</h2>${data.exceptions.map(item=>`<div class="callout"><strong>${esc(item.file||item.code)}</strong><span>${esc(item.message)}</span></div>`).join('')}</section>`:''}<section class="panel section"><div class="section-title"><h2>Draft queue</h2><button class="ghost" data-draft-schedule ${rows.length?'':'disabled'}>Plan Next Two Weeks</button></div>
      <p class="subtle">Original songs get priority in new plans. Every song has a seven-day cooldown. Videos without metadata can be uploaded privately. Add a title, description, tags, and category before scheduling publication. You can leave metadata blank and add it later.</p>
      ${rows.length?`<table><thead><tr><th>Short / file</th><th>Batch / status</th><th>Metadata</th><th>Reservation (Manila)</th><th>Actions</th></tr></thead><tbody>${rows.map(row=>{
        const editable=['AWAITING_METADATA','BATCH_READY','PRIVATE_UPLOADED'].includes(row.status)&&!/DUPLICATE|UNRESOLVED/i.test(row.duplicate_disposition||'');
        const scheduleReady=Boolean(row.scheduled_date&&row.scheduled_time&&Date.parse(this.date(row.scheduled_date)+'T'+this.time(row.scheduled_time)+':00+08:00')>Date.now());
        const missing=['public_title','description','youtube_tags','category'].filter(key=>!String(row[key]||'').trim());
        return `<tr><td><strong>${esc(row.public_title||row.original_filename||row.file_name)}</strong><div class="mono">${esc(row.short_id)}</div><details><summary>Hashed file</summary><span class="mono">${esc(row.current_path||row.current_filename||'Pending intake')}</span></details></td><td>${esc(row.batch_id)}<br>${esc(row.status?.replaceAll('_',' '))}</td><td>${missing.length?'Needs '+esc(missing.map(key=>({public_title:'title',description:'description',youtube_tags:'tags',category:'category'}[key])).join(', ')):'Ready'}</td><td>${esc(this.date(row.scheduled_date))} ${esc(this.time(row.scheduled_time))}<br>${scheduleReady?'Schedule reserved':'Validate schedule first'}<br>${row.youtube_video_id?'YouTube: '+esc(row.youtube_video_id):'Not uploaded'}</td><td><button class="ghost" data-llm-suggest="${esc(row.short_id)}" ${editable&&scheduleReady&&missing.some(key=>key!=='category')?'':'disabled'}>Generate Metadata</button><button class="ghost" data-draft-edit="${esc(row.short_id)}" ${editable?'':'disabled'}>Metadata</button><button class="ghost" data-draft-link="${esc(row.short_id)}" ${editable&&!row.youtube_video_id?'':'disabled'}>Link Private Upload</button><button class="ghost" data-select-batch="${esc(row.batch_id)}">Upload / Schedule</button></td></tr>`;
      }).join('')}</tbody></table>`:'<div class="empty">New drafts will appear here. Existing batches remain available in Batches.</div>'}</section>`;
  },
  calendar(state,esc){
    const model=Array.isArray(state.calendar)?{events:state.calendar}:state.calendar||{},events=model.events||[];
    const month=(/^\d{4}-(0[1-9]|1[0-2])$/.test(state.calendarMonth||'')?state.calendarMonth:null)||new Date(Date.now()+8*3600000).toISOString().slice(0,7);
    const first=new Date(month+'-01T00:00:00Z'),offset=(first.getUTCDay()+6)%7,days=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate(),slots=state.settings?.slots||['20:00'];
    const cells=Array.from({length:offset},()=>'<div class="calendar-padding"></div>'),agenda=[];
    for(let day=1;day<=days;day++){
      const date=month+'-'+String(day).padStart(2,'0'),daily=events.filter(event=>event.pht?.slice(0,10)===date).sort((a,b)=>a.pht.localeCompare(b.pht));
      const growth=state.settings?.cadence==='four-per-week';
      const weekStart=d=>{const v=new Date(d+'T00:00:00Z');v.setUTCDate(v.getUTCDate()-(v.getUTCDay()+6)%7);return v.toISOString().slice(0,10);};
      const weekCount=events.filter(e=>e.pht&&weekStart(e.pht.slice(0,10))===weekStart(date)).length;
      const permitted=!growth||(!daily.length&&weekCount<4&&[1,3,5,0].includes(new Date(date+'T00:00:00Z').getUTCDay()));
      const available=permitted?slots.slice(0,growth?1:slots.length).filter(time=>!daily.some(event=>event.pht?.slice(11,16)===time)&&Date.parse(date+'T'+time+':00+08:00')>Date.now()):[];
      const free=available.length?'<p class="calendar-free">'+esc(available.join(', '))+' available in saved calendar</p>':'';
      if(daily.length||available.length)agenda.push('<article class="agenda-day"><h3>'+esc(date)+'</h3><div>'+daily.map(event=>'<div class="agenda-event"><strong>'+esc(event.pht?.slice(11,16))+'</strong><div>'+esc(event.title||event.shortId)+'<p class="subtle">'+esc(event.state?.replaceAll('_',' '))+' / '+esc(event.batchId||(event.source==='TRACKER'?'Local reservation':'Channel upload'))+'</p></div></div>').join('')+free+'</div></article>');
      cells.push('<article class="calendar-day"><strong>'+day+'</strong>'+daily.slice(0,2).map(event=>'<div class="calendar-event '+(event.source==='YOUTUBE'?'remote':'local')+'"><b>'+esc(event.pht?.slice(11,16))+'</b><span title="'+esc(event.title||event.shortId)+'">'+esc(event.title||event.shortId)+'</span><small>'+esc(event.state?.replaceAll('_',' '))+'</small></div>').join('')+(daily.length?'<button class="ghost" data-calendar-day="'+date+'">View '+daily.length+' video'+(daily.length===1?'':'s')+'</button>':'')+free+'</article>');
    }
    const layout=state.calendarMode==='month'?'<div class="calendar-month-layout"><div class="calendar-week">'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=>'<strong>'+day+'</strong>').join('')+'</div><div class="calendar-grid">'+cells.join('')+'</div></div>':'<div class="calendar-agenda">'+(agenda.join('')||'<div class="empty">No scheduled videos or future slots this month.</div>')+'</div>';
    return '<section class="panel"><div class="section-title"><div><h2>Publication calendar</h2><p class="subtle">Asia/Manila / Local reservations and observed YouTube publication times</p></div><button class="ghost" data-calendar-sync>Sync YouTube</button></div><p class="subtle">'+(model.syncedAt?'Last YouTube sync: '+esc(model.syncedAt):'YouTube has not been synced. Available slots currently reflect the tracker only.')+' Sync before reserving times to include manual uploads.</p><div class="button-row"><button class="ghost" data-calendar-month="-1">Previous</button><label>Month <input type="month" id="calendar-month" value="'+esc(month)+'"></label><button class="ghost" data-calendar-month="1">Next</button><button class="ghost" data-draft-schedule>Reserve Posting Times</button></div><div class="button-row"><button class="ghost" data-calendar-mode="agenda" aria-pressed="'+(state.calendarMode!=='month')+'">Agenda</button><button class="ghost" data-calendar-mode="month" aria-pressed="'+(state.calendarMode==='month')+'">Month grid</button></div><p class="subtle section">20:01-21:00 manual only. Reserved = local plan; YouTube scheduled / published = confirmed at the last sync.</p>'+layout+'</section>';
  }
};
