import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { FileBlob, SpreadsheetFile } from "../../outputs/ralskies-content-engine/work/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs";
import { readTracker } from "../../core/tracker-service.mjs";
import { applyBatch, previewBatch, rollbackBatch } from "../../core/staging-service.mjs";

const root = path.resolve(import.meta.dirname); const trackerPath = path.join(root, "TEST_TRACKER.xlsx"); const transactionPath = path.join(root, "TEST_TRANSACTION.json"); const batchDir = path.join(root, "TEST_BATCH");
const ids = ["RS-522FC2B09FE2", "RS-0AA3EEF2F234"];
const hash = async (filePath) => { const h = crypto.createHash("sha256"); for await (const chunk of (await import("node:fs")).createReadStream(filePath)) h.update(chunk); return h.digest("hex").toUpperCase(); };
const trackerRows = await readTracker(trackerPath); const videos = ids.map((shortId, index) => { const row = trackerRows.find((candidate) => candidate.short_id === shortId); const source = path.join(root, "TEST_SOURCE", index === 0 ? "source-one.mp4" : "source-two.mp4"); const expectedHash = String(row.file_hash).toUpperCase(); return { shortId, source, destination: path.join(batchDir, `${expectedHash.toLowerCase()}.mp4`), sha256: expectedHash }; });
await fs.writeFile(transactionPath, JSON.stringify({ state: "COMPLETE", batches: [{ batchId: "TEST_BULK_01", startDate: "2026-12-01", endDate: "2026-12-02", videos }] }, null, 2));
const sourceHashes = await Promise.all(videos.map((video) => hash(video.source))); const assert = (condition, message) => { if (!condition) throw new Error(message); };
const preview = await previewBatch({ transactionPath, trackerPath, batchId: "TEST_BULK_01", environment: "TEST" }); assert(preview.stagingState === "NOT_STAGED" && preview.valid === 2 && preview.errors.length === 0, "Fixture preview did not pass.");
const first = await applyBatch({ preview, trackerPath, transactionPath, confirmation: "Stage TEST_BULK_01?", environment: "TEST" });
const verify = async (expectedStatus) => { const rows = await readTracker(trackerPath); const current = rows.filter((row) => ids.includes(row.short_id)); const manifest = first.manifestPath; const manifestWb = await SpreadsheetFile.importXlsx(await FileBlob.load(manifest)); const manifestRows = manifestWb.worksheets.getItem("Manifest").getUsedRange().values; assert(current.every((row) => row.status === expectedStatus), `Tracker status mismatch: expected ${expectedStatus}.`); for (const row of current) assert(row.current_path && await fs.stat(row.current_path).then(() => true).catch(() => false), "Staged tracker paths are not all present."); assert(manifestRows.length === 3, `Manifest row count mismatch: ${manifestRows.length}`); for (const video of videos) assert(await hash(video.destination) === video.sha256, `${video.shortId}: staged hash mismatch.`); return { trackerRows: current.length, stagedFiles: videos.length, manifestRows: manifestRows.length }; };
const firstVerification = await verify("BATCH_READY"); const transactionFile = `${transactionPath}.${first.transactionId}.json`; const undo = await rollbackBatch({ transactionFile, trackerPath, environment: "TEST" }); assert(undo.state === "ROLLED_BACK", "Rollback did not complete."); const rolledRows = await readTracker(trackerPath); assert(rolledRows.filter((row) => ids.includes(row.short_id)).every((row) => row.status === "APPROVED" && !String(row.current_path || "").trim()), "Tracker was not restored after rollback."); for (const video of videos) { assert(!(await fs.stat(video.destination).then(() => true).catch(() => false)), `${video.shortId}: staged copy remained after rollback.`); assert(await hash(video.source) === sourceHashes[videos.indexOf(video)], `${video.shortId}: source changed.`); } assert(!(await fs.stat(first.manifestPath).then(() => true).catch(() => false)), "Manifest remained after rollback.");
const secondPreview = await previewBatch({ transactionPath, trackerPath, batchId: "TEST_BULK_01", environment: "TEST" }); const second = await applyBatch({ preview: secondPreview, trackerPath, transactionPath, confirmation: "Stage TEST_BULK_01?", environment: "TEST" }); const secondVerification = await verify("BATCH_READY");
console.log(JSON.stringify({ preview: { valid: preview.valid, errors: preview.errors.length }, apply: { state: first.state, backup: first.backupPath, manifest: first.manifestPath }, verify: firstVerification, undo, rollbackVerified: true, reapply: { state: second.state }, reapplyVerify: secondVerification, sourcesUntouched: true }, null, 2));
